import { FeaturedComparison } from '../../FeaturedComparison';
import type {Metadata} from 'next';
import {notFound,permanentRedirect} from 'next/navigation';import {Header,Footer} from '../../../components';import {blogPosts} from '../../../data';import aug20Meta from '../../../aug20-meta.json';import aug21Meta from '../../../aug21-meta.json';import {aug23BlogBatch} from '../../../aug23-blog';import {sep3BlogBatch} from '../../../sep3-blog';import {sep4BlogBatch} from '../../../sep4-content';import {sep7BlogBatch} from '../../../sep7-content';import {sep8BlogBatch} from '../../../sep8-content';import {sep9BlogBatch} from '../../../sep9-content';import {sep10BlogBatch} from '../../../sep10-content';import {sep18BlogBatch} from '../../../sep18-content';import {sep18bBlogBatch} from '../../../sep18b-content';

const daily=[...sep18bBlogBatch.map(p=>[p.slug,{title:p.title,description:p.description}] as const),...sep18BlogBatch.map(p=>[p.slug,{title:p.title,description:p.description}] as const),...sep10BlogBatch.map(p=>[p.slug,{title:p.title,description:p.description}] as const),...sep9BlogBatch.map(p=>[p.slug,{title:p.title,description:p.description}] as const),...sep8BlogBatch.map(p=>[p.slug,{title:p.title,description:p.description}] as const),...sep7BlogBatch.map(p=>[p.slug,{title:p.title,description:p.description}] as const),...sep4BlogBatch.map(p=>[p.slug,{title:p.title,description:p.description}] as const),...sep3BlogBatch.map(p=>[p.slug,{title:p.title,description:p.description}] as const),...aug23BlogBatch.map(p=>[p.slug,{title:p.title,description:p.description}] as const),...Object.entries(aug21Meta),...Object.entries(aug20Meta)].map(([slug,p])=>({slug,title:p.title,excerpt:p.description}));
const latest=blogPosts.filter(p=>p.detail?.published==='2026-09-02');
const earlier=blogPosts.filter(p=>p.detail?.published!=='2026-09-02');
const allPosts=[...daily.slice(0,24),...latest,...daily.slice(24),...earlier];

export function generateStaticParams(){const n=Math.max(1,Math.ceil(allPosts.length/20));return Array.from({length:n},(_,i)=>({page:String(i+1)}))}

export async function generateMetadata({params}:{params:Promise<{page:string}>}):Promise<Metadata>{const {page}=await params;const n=Number(page);return {title:`Billing Operations Blog – Page ${n}`,description:`Browse page ${n} of practical billing-operations guides for documented handoffs, evidence checks, exception routing, and owner review.`,alternates:{canonical:`/blog/page/${n}`}}}

export default async function BlogPage({params}:{params:Promise<{page:string}>}){const {page}=await params;const n=Number(page),total=Math.max(1,Math.ceil(allPosts.length/20));if(page==='1')permanentRedirect('/blog');if(!Number.isInteger(n)||n<1||n>total)notFound();const posts=allPosts.slice((n-1)*20,n*20);return <><Header/><main className="section"><div className="container"><p className="eyebrow">Philippines staffing blog</p><h1>Blog page {n}</h1><div className="cards">{posts.map(p=><a className="card" href={`/blog/${p.slug}`} key={p.slug}><h2>{p.title}</h2><p>{p.excerpt}</p></a>)}</div><nav className="pagination" aria-label="Blog pages">{Array.from({length:total},(_,i)=><a aria-current={i+1===n?'page':undefined} href={i===0?'/blog':`/blog/page/${i+1}`} key={i}>{i+1}</a>)}</nav></div>{n===2&&<FeaturedComparison />}</main><Footer/></>}
