export type Aug23ResearchRecord = {
  slug: string; title: string; excerpt: string; published: '2026-08-23'; datePublished: '2026-08-23'; updated: '2026-08-23'; body: string[];
};

const common = (question: string, method: string, detail: string, limits: string, conclusion: string, sources: string[]) => [
  'Research date: 2026-08-23. Scope: operational research for an outsourced medical billing support team. This article describes evidence handling and role boundaries. It is not legal, clinical, coding, payer-contract, or financial advice.',
  `Research question: ${question}`,
  `Methodology and evidence scope: ${method} The review compares the stated operational question with primary guidance from CMS, HHS, NIST, and CAQH. It uses those sources to define observable records and decisions. It does not claim that a national rule or technical framework predicts the performance of one billing queue. Facts from the cited sources are kept separate from the analysis that follows.`,
  detail,
  'For an outsourced billing service, the useful unit is a reviewable work item, not a vague promise to improve revenue. The item needs a stable claim, invoice, account, or encounter reference; the source consulted; the date and time; the observed result; the unresolved question; and the person who can decide the next step. A Philippines-based specialist may prepare that record when the organization has granted the required access. The specialist should not fill an evidence gap with a likely answer simply because a queue is aging.',
  'The evidence register should retain the original payer message, remittance, system export, approved source document, or correspondence reference. A copied summary can help a reviewer, but it should not replace the source. When two systems disagree, preserve both values and describe the comparison. When a later correction appears, link it to the prior version rather than overwriting history. This makes a disagreement visible to the billing owner and prevents the latest entry from being mistaken for the original fact.',
  'The analysis should label each finding. Source-supported means the record states the fact being tested. Calculated means the team derived an interval, total, or comparison from stated inputs. Conflicting means two permitted sources disagree. Unavailable means the needed source was not present or could not be accessed. Owner-interpreted means a qualified person has applied a policy, coding rule, contract term, or clinical judgment. These labels keep a prepared evidence packet from sounding more certain than it is.',
  'A measured result should state what was reviewed, when it was reviewed, and which records were excluded from the observation.',
  'A small sample should contain ordinary items and boundary items. Include clean-looking records, missing documents, duplicate-looking records, late responses, corrected versions, unexplained balances, and items with restricted information. Sampling only routine work answers whether routine work is easy. It does not answer whether the workflow catches the cases most likely to need escalation. Report the denominator, exclusions, observation date, and missing fields so a reader can judge the scope of the result.',
  'The support role has a practical stopping rule. It can compare permitted fields, retrieve approved evidence, record payer wording, prepare a chronology, and route one focused question. It stops before selecting a code, interpreting medical necessity, approving a refund or write-off, changing a balance, promising coverage, deciding payer responsibility, or sending a consequential response without approval. The exact boundary belongs in the site SOP and the access matrix, not in an informal chat instruction.',
  'The owner review should examine whether the evidence is sufficient for the decision, not whether the specialist sounded confident. A good review records the decision, the source relied upon, the exception that was accepted or rejected, and any follow-up date. If the owner cannot decide because a payer rule or source record is ambiguous, the honest status is unresolved. That status is operationally useful because it preserves the next question and prevents premature closure.',
  'This method has limits. It cannot establish a payer obligation from an administrative field, certify coding or clinical compliance, prove that a claim will be paid, or turn a sample into a market statistic. It also depends on source retention, authorized access, accurate timestamps, current policy text, and a reviewer who understands the applicable rule. Privacy restrictions may require the team to minimize copied details and keep sensitive evidence inside the approved system.',
  limits,
  conclusion,
  'Sources consulted:',
  ...sources,
];

export const aug23Research: Aug23ResearchRecord[] = [
  {
    slug: 'research-medical-billing-remittance-adjustment-lineage-2026',
    title: 'Medical Billing Remittance Adjustment Lineage Research: Can Each Balance Change Be Explained?',
    excerpt: 'A source-led study of adjustment codes, remittance lines, account postings, and the owner decisions that must remain outside preparation work.',
    published: '2026-08-23', datePublished: '2026-08-23', updated: '2026-08-23',
    body: common('Can a billing team trace an adjustment from the payer remittance to the account posting without confusing a reported reason with an approved financial conclusion?', 'Freeze a cohort of remittance lines and their related account events. Capture the claim control number, service date, remittance line, adjustment group and reason code, billed amount, allowed or paid amount when stated, posting transaction, batch reference, and later correction. Compare the remittance wording with the local posting rule. This tests lineage and reconciliation, not whether an adjustment is contractually correct.', 'The strongest test follows one line through the whole chain: remittance source, posting batch, account transaction, later reversal or correction, and final reviewer note. A matching amount is only a starting point because two unrelated events can share an amount. A specialist should record the proposed match and the evidence for it, then route unusual group codes, patient-responsibility consequences, and any posting rule that is unclear. The owner can then decide whether the source supports the adjustment and whether a second review is needed. This distinction matters when a remote queue prepares many routine postings but only a smaller set needs financial judgment.', 'The method cannot determine that an adjustment is valid merely because a code was present, and it cannot approve a refund, transfer, write-off, or patient balance.', 'The evidence-led conclusion is that adjustment lineage is a useful control for outsourced billing support when each posting points back to a remittance source and every unresolved interpretation is routed. It can show which changes are traceable, which are calculated, and which need owner review. It cannot convert a remittance code into an automatic financial decision.', ['https://www.cms.gov/regulations-and-guidance/guidance/manuals/internet-only-manuals-ioms-items/cms018912', 'https://www.cms.gov/medicare/claims-processing', 'https://www.cms.gov/medicare/coding-billing'])
  },
  {
    slug: 'research-medical-billing-claim-receipt-cohort-2026',
    title: 'Medical Billing Claim Receipt Cohort Research: What Does a Payer Acknowledgment Prove?',
    excerpt: 'A bounded study of submission identifiers, acknowledgments, rejections, and the difference between transport evidence and claim acceptance.',
    published: '2026-08-23', datePublished: '2026-08-23', updated: '2026-08-23',
    body: common('Does the available transaction trail establish payer receipt of a particular claim version, or only show that a billing message left the sending system?', 'Define the cohort by claim version and submission event. Preserve the release timestamp, transmission identifier, clearinghouse response, payer acknowledgment, rejection, correction, resubmission, and timezone. Separate prepared, sent, received, accepted, rejected, adjudicated, and paid as different observations. Compare records near a stated filing boundary with ordinary records so the method does not study only easy successes.', 'The useful result is an event chronology rather than a single receipt flag. For each claim, record the earliest event that the named source supports and retain later responses as separate events. A rejection can coexist with proof of an earlier transmission. A missing payer acknowledgment should remain missing even if a local status says sent. If the team calculates elapsed time, show the two timestamps and the timezone conversion. This gives the billing owner a way to distinguish a transport question from a filing-rule question and keeps a support queue from selecting the most favorable event.', 'The transaction trail may be incomplete, a payer acknowledgment may describe only one interface layer, and a transport event cannot prove adjudication or payment. A deadline also needs its authoritative rule before an interval can be interpreted.', 'The evidence-led conclusion is that receipt research can clarify which transaction events are documented for each claim version. It gives the billing owner a defensible chronology and a focused question about missing evidence. It cannot promise timely filing, acceptance, payer fault, or appeal success from a transmission record alone.', ['https://www.cms.gov/medicare/claims-processing', 'https://www.caqh.org/core/operating-rules', 'https://www.gao.gov/products/gao-14-704g'])
  },
  {
    slug: 'research-medical-billing-service-date-cohort-2026',
    title: 'Medical Billing Service-Date Cohort Research: Separating Encounter Timing From Claim Timing',
    excerpt: 'A research method for comparing service dates, encounter records, claim versions, and payer responses without collapsing different clocks into one.',
    published: '2026-08-23', datePublished: '2026-08-23', updated: '2026-08-23',
    body: common('When a billing record contains several dates, which source supports the service event being studied and which dates belong only to preparation, submission, correction, or adjudication?', 'Use the encounter or service event as the cohort boundary, then link each claim version, charge entry, submission, response, payment, and correction without replacing one date with another. Record the source label, timestamp, timezone, document version, and whether a date was entered, calculated, or returned by a payer. Stratify missing and conflicting dates instead of dropping them silently.', 'A date map should answer a different question at each boundary. The service date describes the event under review, the entry date describes when staff recorded it, the submission date describes a transaction, and the response date describes a payer or clearinghouse event. None should be silently promoted to the authoritative date for every purpose. Include records that cross midnight, use a correction, or lack a timezone because those cases reveal whether the workflow has a real rule or relies on intuition. The owner decides which date controls a filing, coding, or contract question.', 'A date comparison cannot establish coverage, coding correctness, medical necessity, or payer responsibility. Different systems may use different clocks and retention periods, and an amended claim may answer a different question from the original claim.', 'The evidence-led conclusion is that date lineage helps an outsourced billing team explain whether a source supports an encounter fact, a claim event, or a payer event. It narrows review and exposes gaps. It does not make matching dates proof of a payable claim or resolve a policy interpretation reserved for the owner.', ['https://www.cms.gov/medicare/claims-processing', 'https://www.cms.gov/medicare/coding-billing', 'https://www.hhs.gov/hipaa/for-professionals/privacy/index.html'])
  },
  {
    slug: 'research-medical-billing-payer-message-history-2026',
    title: 'Medical Billing Payer Message History Research: Measuring Whether Follow-Up Is Reconstructable',
    excerpt: 'A study of portal notes, call references, response wording, and follow-up ownership for billing teams handling unresolved payer work.',
    published: '2026-08-23', datePublished: '2026-08-23', updated: '2026-08-23',
    body: common('Can another authorized reviewer reconstruct what a billing team asked a payer, what the payer returned, and what decision remains open?', 'Freeze a sample of follow-up items with at least one payer contact or portal event. Record the claim or account reference, contact channel, date and time, transaction or call reference, exact response wording where permitted, requested documents, stated deadline, next action, and owner. Compare the note with the underlying claim and remittance. Count missing references and unresolved responses as findings rather than treating contact as completion.', 'Message quality has two parts: retrieval and interpretation. The first asks whether a reviewer can find the original portal event, call reference, or correspondence. The second asks whether the note distinguishes the payer wording from the staff member’s interpretation. Reviewers should mark those parts separately. A follow-up may be complete as a contact attempt but still open as a decision. The queue should therefore carry both a contact status and a decision status, with a dated next action for each unresolved item.', 'A local note is evidence that a note was entered, not necessarily proof that the payer accepted the question or made the conclusion the note implies. Privacy rules may limit what can be copied, and a representative statement may need qualified interpretation.', 'The evidence-led conclusion is that message-history research can measure whether follow-up is traceable and whether each item has a real next owner. It can improve handoffs without asking a support specialist to interpret a payer rule. It cannot establish entitlement, guarantee a response, or authorize a balance change.', ['https://www.cms.gov/medicare/claims-processing', 'https://www.hhs.gov/hipaa/for-professionals/privacy/index.html', 'https://www.nist.gov/cyberframework'])
  },
  {
    slug: 'research-medical-billing-document-version-lineage-2026',
    title: 'Medical Billing Document Version Lineage Research: Finding the Record Used for a Decision',
    excerpt: 'A source-control study for orders, authorizations, remittances, and billing documents that change over time or arrive in multiple copies.',
    published: '2026-08-23', datePublished: '2026-08-23', updated: '2026-08-23',
    body: common('Can a billing reviewer identify which document version supported a preparation or approval decision when an order, authorization, remittance, or correspondence is later amended?', 'Select records with replacements, corrections, duplicate files, or revised payer messages. Preserve the original filename or identifier, received timestamp, effective period, supersession notice, source location, claim or account link, and the user who attached or approved the document. Test whether the decision record names the version actually used. Keep a later document linked, not substituted, when both have relevance.', 'A version register should distinguish a new document from a new copy. Compare identifiers, received times, effective dates, supersession language, and substantive fields, then record why the reviewer treated two files as related or separate. If a decision was made before an amendment arrived, preserve that chronology and route the impact question to the owner. If no one can identify the source version, the right finding is reproducibility failure, even when the current file appears complete. This is especially important when remote staff work from a shared queue with changing attachments.', 'Version lineage does not determine whether a document is authentic, clinically sufficient, contractually controlling, or legally dispositive. Access and retention rules may prevent the support role from inspecting some content.', 'The evidence-led conclusion is that document lineage can show whether a billing decision is reproducible from an identified source version. It lets an owner distinguish an amended fact from an administrative duplicate and route the right question. It cannot certify document sufficiency or let support staff make a clinical, coding, legal, or financial judgment.', ['https://www.hhs.gov/hipaa/for-professionals/security/index.html', 'https://csrc.nist.gov/pubs/sp/800/66/r2/final', 'https://www.healthit.gov/topic/safety/safer-guides'])
  },
];
