import { type ResearchSeed, type ResearchSource } from './sep22b-research';
import { oct5LiteralResearchBodies } from './oct5-research-literal-bodies';

const published = '2026-10-06' as const;
const checked = 'October 5, 2026';
const featuredImage = '/aug20-research-heroes/research-medical-billing-remittance-batch-reconciliation.png';

const greenBook: ResearchSource = { title: 'Standards for Internal Control in the Federal Government: 2025 Revision', publisher: 'U.S. Government Accountability Office', url: 'https://www.gao.gov/greenbook', use: 'quality information, control activities, documentation, segregation of duties, and monitoring' };
const nist: ResearchSource = { title: 'Security and Privacy Controls for Information Systems and Organizations, SP 800-53 Revision 5', publisher: 'National Institute of Standards and Technology', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', use: 'audit records, least privilege, controlled change, and information integrity' };
const ftc: ResearchSource = { title: 'Protecting Personal Information: A Guide for Business', publisher: 'U.S. Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business-0', use: 'data inventory, limited access, secure handling, service-provider oversight, and disposal' };
const fasb: ResearchSource = { title: 'Revenue Recognition: ASU 2014-09, Revenue from Contracts with Customers (Topic 606)', publisher: 'Financial Accounting Standards Board', url: 'https://fasb.org/projects/recently-completed-projects/revenue-recognition-summary', use: 'authoritative context for revenue judgments reserved to qualified accounting owners' };

const seeds: ResearchSeed[] = [
  {
    slug: 'research-outsourced-billing-rendered-invoice-source-equality-2026', topic: 'rendered invoice and approved source equality',
    title: 'Rendered Invoice Equality Research: Did the Approved Data Survive Document Generation?',
    excerpt: 'A field-and-artifact study comparing approved billing data with the exact customer-facing PDF or portal document without treating a balanced total as proof.',
    question: 'For every released invoice version, do the customer-facing fields, lines, totals, references, and attachments equal the approved source packet after templates, formatting, pagination, and delivery transformations?',
    decision: 'whether invoice preparation has enough artifact-level evidence to delegate rendering checks while commercial, tax, accounting, and release decisions remain with authorized owners',
    unit: 'one released invoice artifact version linked to one approved source packet, rendering event, destination, and release decision',
    population: 'all invoices rendered or regenerated in the selected cycle, including multi-page documents, zero and negative lines, long descriptions, non-ASCII text, multiple currencies, credits, attachments, portal conversions, corrected versions, inaccessible artifacts, and unresolved mismatches',
    evidence: 'invoice and version identifier; approved source snapshot; template and renderer version; generation time; legal and bill-to names; dates; purchase-order reference; line descriptions, quantities, rates and amounts; tax fields supplied by owners; subtotal, credits and total; currency; payment instructions; page count; attachment manifest; document hash; approver; release event; destination; and supersession link',
    states: 'exact field match, supported format-only change, truncation, wrapping ambiguity, omitted line, duplicated line, stale template value, wrong attachment, arithmetic mismatch, currency-label mismatch, approved exception, release blocked, released, superseded, inaccessible, and unresolved',
    tests: 'compare structured source fields with extracted artifact fields; recalculate totals from displayed lines; inspect first, middle, and last pages; preserve Unicode and leading zeros; test long descriptions and negative values; hash the approved artifact; verify attachments by name and content; trace regenerated files to supersession; and independently review every content difference',
    interpretation: 'A correct database record does not prove that the delivered artifact is correct. A balanced PDF can still omit a line, show a stale address, lose a purchase-order reference, or attach the wrong support. Source approval, rendering fidelity, release, and delivery are separate findings.',
    limitations: 'PDF extraction, fonts, accessibility tags, portal transformations, image-only pages, localization, template logic, tax fields, confidential attachments, and inaccessible delivered copies constrain comparison. The study cannot approve an invoice, decide tax or contract treatment, or establish customer receipt.',
    service: '/services/invoice-preparation', serviceLabel: 'Review invoice-preparation support', sources: [greenBook, nist, ftc],
  },
  {
    slug: 'research-outsourced-billing-recurring-schedule-drift-2026', topic: 'recurring billing schedule drift',
    title: 'Recurring Billing Schedule Drift Research: Did the Live Schedule Depart From the Approved Terms?',
    excerpt: 'A version-and-calendar study of recurring charge dates, frequencies, quantities, prices, pauses, end dates, and live system schedules.',
    question: 'Across active recurring accounts, where does the live billing schedule differ from the last approved schedule, and which source event or missing decision explains each difference?',
    decision: 'whether recurring-billing maintenance can be delegated as comparison and exception preparation without transferring authority over terms, pricing, dates, cancellation, or invoice release',
    unit: 'one recurring charge component for one customer, product or service, approved term version, live schedule version, and expected billing occurrence',
    population: 'all active, paused, future-dated, cancelled, expired, amended, migrated, manually overridden, failed, and unresolved recurring schedules expected to exist or produce an event during the observation window',
    evidence: 'account and schedule identifiers; approved order or amendment locator; product; quantity; price and currency source; cadence; anchor date; timezone; start and end dates; pause and resume evidence; renewal state; live configuration snapshot; change history; expected and actual event; draft or released invoice; exception owner; approval; and correction lineage',
    states: 'aligned, cadence drift, anchor-date drift, quantity drift, price-source conflict, end-date conflict, pause not reflected, unintended active schedule, missing schedule, duplicate schedule, migration difference, owner interpretation required, corrected, inaccessible, and unresolved',
    tests: 'derive expected occurrences from the preserved approved version; compare live fields without overwriting either state; inspect month-end and leap-date rules; test pauses, resumptions, amendments, and end dates; trace every override; search for duplicate active schedules; compare expected events with drafts and releases; and second-review each proposed schedule change',
    interpretation: 'A schedule that runs successfully can still implement the wrong approved version, while a difference may be a valid amendment not yet linked to the system record. Drift detection identifies an evidence gap; it does not decide which commercial term should govern.',
    limitations: 'Contract interpretation, renewal clauses, proration, business-day conventions, timezone behavior, migrations, tax, currency, bundled products, and incomplete version history can prevent a definitive result. The study cannot change a schedule, select a price, cancel service, or authorize a charge.',
    service: '/services/subscription-billing-support', serviceLabel: 'Review subscription-billing support', sources: [greenBook, nist, fasb, ftc],
  },
  {
    slug: 'research-outsourced-billing-partial-credit-application-lineage-2026', topic: 'partial credit memo application lineage',
    title: 'Partial Credit Application Research: Where Did Each Approved Credit Component Go?',
    excerpt: 'A component-level study connecting an approved credit memo with invoice applications, residual value, reversals, reapplications, and customer-account effects.',
    question: 'When a credit memo is applied in parts, can every component be traced from its approved source through each invoice application, reversal, transfer, remaining balance, and final disposition?',
    decision: 'whether credit administration support can prepare an application and reconciliation packet while approval, accounting, tax, refund, transfer, and customer-balance decisions stay with qualified owners',
    unit: 'one separately identifiable credit component in one currency linked to one approval, application event, affected invoice, and current disposition',
    population: 'all approved credits that were partly applied, split, reversed, transferred, expired, refunded, left open, corrected, or otherwise changed during the selected period, including zero residuals, duplicate-looking events, inaccessible history, and unresolved balances',
    evidence: 'credit memo and version; originating invoice or event; approved amount, tax component and currency; reason and source locator; approval scope; customer account; application event and timestamp; target invoice and line where available; amount applied; reversal; reapplication; refund or transfer request; residual calculation; posting reference; reviewer; and closing state',
    states: 'approved unapplied, partly applied, fully applied, wrong-invoice candidate, duplicate-application candidate, reversed, reapplied, refund proposed, transfer proposed, residual mismatch, currency conflict, tax review required, closed, inaccessible, and unresolved',
    tests: 'freeze original approved components; reconcile opening value plus authorized changes to applications, reversals, refunds, transfers, and closing residual; preserve gross and tax components; trace each application both directions; inspect same-amount events; verify reversal and reapplication pairs; compare account and document currencies; and independently recalculate every residual mismatch',
    interpretation: 'A zero credit balance does not prove correct use: value may have reached the wrong invoice, been applied twice and reversed, or been transferred without the expected approval. Arithmetic, application identity, account treatment, and customer entitlement require separate evidence.',
    limitations: 'Tax rules, currency conversion, accounting policy, invoice disputes, system netting, customer hierarchies, refunds, write-offs, migrations, and missing transaction history limit reconstruction. The study cannot approve a credit, choose an invoice, determine liability, release funds, or prescribe an accounting entry.',
    service: '/services/credit-memo-administration', serviceLabel: 'Review credit-memo administration support', sources: [greenBook, nist, fasb, ftc],
  },
  {
    slug: 'research-outsourced-billing-dispute-hold-synchronization-2026', topic: 'billing dispute hold synchronization',
    title: 'Dispute Hold Synchronization Research: Do Billing and Collections Share the Same State?',
    excerpt: 'A cross-system state study comparing dispute scope, collection restrictions, invoice flags, owner decisions, effective times, and resumed activity.',
    question: 'For every open or recently resolved billing dispute, do invoice, account, collections, customer-support, and workflow records show a consistent scoped hold state at the time work is performed?',
    decision: 'whether dispute documentation and collections follow-up have a reproducible handoff without allowing support staff to decide liability, impose or release restrictions, or select collection strategy',
    unit: 'one dispute version with one declared account, document or line scope linked to the corresponding hold representation in each in-scope system',
    population: 'all disputes opened, changed, escalated, narrowed, expanded, resolved, reopened, or closed during the window, plus collection actions and billing events touching their declared scope, including partial disputes, inherited account flags, sync failures, inaccessible systems, and unresolved scope',
    evidence: 'dispute identifier and version; customer and affected invoices or lines; source wording; amount and currency; opened and effective times; scope; owner; requested restriction; approval; each system flag and timestamp; outbound contact and billing events; resolution evidence; release decision and effective time; sync response; resumed work; and reopen history',
    states: 'states aligned, scope mismatch, timing lag, collections active during effective hold, billing active during effective hold, overbroad restriction, stale flag, missing flag, resolution pending, release approved not propagated, resumed after release, reopened, inaccessible, and unresolved',
    tests: 'construct a time-ordered state table rather than comparing current screens; preserve scope at every version; compare each system at identical timestamps; inspect activity during lag windows; sample aligned items as well as exceptions; separate technical propagation from owner approval; trace release before resumed work; and second-review every potentially restricted action',
    interpretation: 'Matching current statuses cannot prove that systems agreed when a contact or invoice event occurred. A lag may be technical, procedural, or a deliberate owner decision. The evidence should identify the first unsupported transition without declaring fault or the merits of the dispute.',
    limitations: 'System clocks, batch interfaces, manual queues, legal restrictions, contract terms, customer communications, partial scope, retention, emergency controls, and owner response time constrain reconstruction. The study cannot validate a dispute, stop or resume collections, concede an amount, or provide legal advice.',
    service: '/services/dispute-documentation', serviceLabel: 'Review dispute-documentation support', sources: [greenBook, nist, ftc],
  },
  {
    slug: 'research-outsourced-billing-close-package-control-total-integrity-2026', topic: 'month-end billing close package control-total integrity',
    title: 'Billing Close Control-Total Research: Can the Package Be Rebuilt From Frozen Sources?',
    excerpt: 'A reproducibility study of frozen extracts, population totals, adjustments, exceptions, approvals, reruns, and the final month-end billing package.',
    question: 'Can a second reviewer rebuild every control total in the billing close package from frozen named sources and explain every difference between preliminary, adjusted, and final versions?',
    decision: 'whether month-end billing support produces a reviewable operational package while accounting conclusions, materiality, journal entries, estimates, and sign-off remain with qualified owners',
    unit: 'one declared control total for one source population, measure, currency, cutoff, extraction version, transformation, and close-package version',
    population: 'all totals and supporting populations used in the selected billing close, including invoices, credits, cash applications, unapplied cash, holds, unbilled candidates, adjustments, reruns, late records, cancelled documents, inaccessible sources, and unresolved variances',
    evidence: 'control identifier; purpose; source system and report or query; extraction timestamp and timezone; parameters; row count; amount and currency; hash or protected locator; transformation steps; exclusions; preliminary result; approved adjustments; rerun reason; final result; variance; preparer; reviewer; owner conclusion; sign-off; and supersession link',
    states: 'source frozen, reproducible, parameter mismatch, row-count mismatch, amount mismatch, currency mixed, exclusion unsupported, late movement disclosed, adjustment approved, rerun linked, unexplained variance, owner review pending, signed off, superseded, inaccessible, and unresolved',
    tests: 'rerun calculations from retained inputs; compare row counts before amounts; separate currencies and signed values; test filters and cutoff timestamps; reconcile each version through a movement schedule; retain rather than overwrite preliminary totals; trace adjustments to approvals; inspect late and cancelled records; and require independent reproduction of every material or unexplained difference',
    interpretation: 'A spreadsheet whose totals agree internally may still omit a source population, mix cutoffs, or contain pasted values. Reproduction shows how a number was built; it does not establish accounting completeness, materiality, recognition, or the correct financial-statement treatment.',
    limitations: 'Source retention, mutable reports, spreadsheet behavior, timezone cutoffs, currency, estimates, inaccessible systems, accounting policy, consolidation, and post-close events constrain conclusions. The study cannot approve a close, set materiality, post a journal, make an estimate, or offer an audit opinion.',
    service: '/services/month-end-billing-support', serviceLabel: 'Review month-end billing support', sources: [greenBook, nist, fasb],
  },
];

const fieldNotes: Record<string, string[]> = {
  'research-outsourced-billing-rendered-invoice-source-equality-2026': [
    'Artifact comparison should begin with the final released bytes, not a convenient regeneration. Preserve the delivered document hash and the approved source snapshot before extraction. Compare identity, dates, references, line membership, signed values, currency labels, totals, payment instructions, and attachment membership as separate assertions. Formatting normalization may remove harmless whitespace, but it must never hide lost leading zeros, minus signs, decimal precision, page continuations, or non-ASCII characters. A renderer test succeeds only when the customer-facing representation remains attributable to the approved version.',
    'A useful stress case is a seven-page invoice whose last line carries a negative quantity and whose purchase-order value begins with zero. The source totals and PDF total may agree even if the line wraps under the wrong heading or the reference loses its first character. The reviewer records the precise field difference, identifies the template or transformation step, and blocks release or routes correction under policy. The researcher does not rewrite commercial wording, choose a tax label, or infer that an apparently small difference is immaterial.',
    'The buyer should receive a difference register organized by artifact field and transformation stage, not a single pass rate. Report documents unavailable after delivery, extraction uncertainty, mismatched attachments, supported display-only differences, content differences, and superseded versions. This makes recurring renderer defects distinguishable from isolated source errors and lets the owner decide whether template repair, source correction, regeneration, or customer communication is appropriate.',
  ],
  'research-outsourced-billing-recurring-schedule-drift-2026': [
    'Schedule drift is best represented as two versioned timelines. One timeline contains approved commercial events; the other contains system configuration and generated billing events. Join them only through stable account, component, and version keys. Comparing today’s configuration with today’s contract record misses temporary drift that already generated a draft or invoice. Preserve each state before and after amendments, pauses, migrations, and manual edits so an authorized reviewer can locate the first divergence.',
    'Consider an annual service with a month-end anchor that is paused, resumed, and later amended. A system may move the anchor by one day when February is involved, restore the old quantity on resume, or keep a schedule active after the amended end date. These are three different tests and three different owner questions. The analysis calculates expected occurrences under the explicitly cited approved version; it does not decide that the version is enforceable or that a resulting charge should be released.',
    'Reporting should distinguish field drift from event consequences. Count mismatched cadence, anchor, quantity, price reference, end date, and pause state, then separately show drafts or releases affected by each difference. Include aligned schedules and missing source records in the denominator. A concentrated pattern after a migration supports a targeted configuration review, but it remains an inference until change logs and migration rules identify the mechanism.',
  ],
  'research-outsourced-billing-partial-credit-application-lineage-2026': [
    'Build the credit as a component ledger rather than treating the memo header as one undivided balance. Preserve principal, tax, fee, currency, and other owner-defined components when the source supports them. Each application, reversal, transfer, or refund becomes a signed event against a component and target. The closing residual is calculated from those events, while the system-displayed balance remains a separate observed value. Differences are exceptions, not values to be plugged into the reconciliation.',
    'A revealing scenario is a credit approved for two invoice lines, partly used on the original invoice, reversed during a correction, and later applied to another document in the same account. A zero header balance cannot show whether the reversal restored the correct component or whether reapplication was authorized. The packet should expose event order, target documents, currencies, approval scope, and remaining component value. It must not recommend a refund or customer entitlement merely because cash-equivalent value appears unused.',
    'The operational result is a lineage map and movement schedule. Report linked applications, wrong-target candidates, duplicate candidates, unmatched reversals, residual mismatches, owner-pending proposals, and inaccessible events by value and count. Sample fully consumed credits because apparent closure can conceal misapplication. The buyer can then correct keys, approval references, or application workflow while finance and tax owners retain decisions over balance treatment.',
  ],
  'research-outsourced-billing-dispute-hold-synchronization-2026': [
    'A point-in-time matrix is the core instrument: rows are dispute versions and columns are billing, collections, support, and workflow systems at a declared timestamp. Every flag needs its own effective time, scope, source, and actor. The matrix should be replayed at meaningful events such as an outbound contact, draft generation, invoice release, resolution, and collections restart. That design detects a harmful timing gap that a current-state screenshot would erase.',
    'Partial scope is the difficult case. A customer may dispute one line while acknowledging the rest of an invoice, or dispute one invoice within an account that has other collectible balances. The research records the exact supplied scope and how each system represents it. An account-wide flag may be intentionally conservative or improperly broad; a line-level flag may be unavailable in a downstream tool. Either condition requires an owner decision and must not be silently translated by support staff.',
    'Publish transition evidence rather than naming a responsible team from correlation. Show the time from approved restriction to each propagated flag, activity observed during the interval, release-to-resumption time, stale restrictions, and missing scope. Separate approved exceptions from unexplained differences. This lets the buyer improve integration, escalation, or manual compensating controls without implying that every timing difference violated a contract or law.',
  ],
  'research-outsourced-billing-close-package-control-total-integrity-2026': [
    'Start with an inventory of claims made by the close package. A row count, invoice value, unapplied-cash balance, credit total, or exception count is a separate control total with its own source, grain, currency, signs, cutoff, and transformation. Build a dependency map from frozen inputs to intermediate schedules to the presented total. A screenshot can support what someone saw, but it cannot replace the extract or calculation needed for reproduction.',
    'Version movement deserves its own reconciliation. Suppose a preliminary invoice register is rerun after late approvals and the final workbook also contains an owner-approved manual adjustment. The package should bridge preliminary source total, named late records, cancelled or corrected documents, approved adjustment, and final total. Replacing the first workbook with the last loses evidence of the close process. Preserving both versions lets the reviewer test whether the change belongs to source activity, a transformation, or an owner judgment.',
    'Report reproducibility at the level of each declared total and disclose totals that cannot be rebuilt. Also report parameter differences, row-count differences, mixed currency, unsupported exclusions, pasted values, late movements, and unresolved variance. A high percentage of reproducible totals is useful only when omitted and inaccessible populations stay visible. The owner can then decide whether to refreeze a source, repair a query, explain a variance, or defer sign-off.',
  ],
};

const buildBody = (seed: ResearchSeed) => {
  const literalBody = oct5LiteralResearchBodies[seed.slug];
  if (!literalBody) throw new Error(`Missing literal October 5 research body for ${seed.slug}`);
  return literalBody;
};

export const oct5ResearchBatch = seeds.map((seed) => ({
  slug: seed.slug, title: seed.title, excerpt: seed.excerpt, published, datePublished: published, updated: published,
  featuredImage, body: buildBody(seed), serviceCta: { href: seed.service, label: seed.serviceLabel, title: 'Turn the research design into a bounded billing routine', body: 'Define the population, evidence, stopping points, review owner, and approval boundary before assigning volume.' },
}));

export const oct5ResearchTopics = seeds.map(({ slug, topic, sources }) => ({ slug, topic, sources }));
