const published = '2026-09-10' as const;
const blogImage = '/aug20-heroes/billing-operations-payer-response-aging-review.png';
const researchImage = '/aug20-research-heroes/research-medical-billing-remittance-batch-reconciliation.png';

type BlogSeed={slug:string;title:string;situation:string;sources:string;risk:string;owner:string;test:string};
const blogSeeds:BlogSeed[]=[
 {slug:'medical-billing-277ca-acknowledgment-exception-desk',title:'Work the 277CA Exception Desk Before Claim Status Follow-Up',situation:'claim-level acknowledgments after an outbound claim batch',sources:'the released batch, interchange receipt, 999 when present, 277CA, clearinghouse identifiers, and local claim version',risk:'an accepted file can contain rejected claims, and an unlinked response can look like no response',owner:'billing transmission owner',test:'every scoped claim version links to a source response or a named missing-response exception'},
 {slug:'medical-billing-provider-enrollment-change-cutover-log',title:'Keep a Cutover Log for Provider Enrollment Changes',situation:'a payer enrollment relationship changing around an effective date',sources:'the dated payer source, provider and location relationship, prior and current configuration, claim dates, acknowledgments, and change approval',risk:'an approval date can be mistaken for an effective date and a current portal screen can erase useful history',owner:'provider enrollment owner',test:'each boundary-date claim has a source-supported state and the prior configuration remains traceable'},
 {slug:'medical-billing-claim-attachment-control-number-match',title:'Match Claim Attachments With More Than a Patient Name',situation:'a requested-records packet being associated with a claim',sources:'the payer request, claim version, claim and attachment control numbers, service period, document index, authorization, transmission, and receipt',risk:'the right document can be attached to the wrong claim version or request',owner:'records release and qualified billing owner',test:'request, packet version, claim, approval, delivery, and receipt form one chain'},
 {slug:'medical-billing-patient-statement-suppression-review',title:'Review Patient Statement Suppressions Before the Next Cycle',situation:'account holds active at a frozen statement-cycle cutoff',sources:'the suppression type, source reason, start and review dates, system rule or manual event, balance snapshot, correspondence, and owner',risk:'an old hold can hide work while an expired review date is mistaken for permission to release a statement',owner:'patient financial services owner',test:'every hold has current support, an approved release, or a named unresolved question'},
 {slug:'medical-billing-zero-pay-remittance-routing',title:'Route Zero-Pay Remittances by Evidence, Not by Balance Alone',situation:'zero-pay remittance lines entering the posting and follow-up queues',sources:'claim and service-line references, paid and adjustment amounts, group and reason codes, payer text, trace, deposit, and posting state',risk:'a zero amount can hide a denial, transfer, reversal, crossover message, or information-only response',owner:'remittance and accounting owner',test:'each source line links to an approved route without netting away its component evidence'},
 {slug:'medical-billing-recoupment-offset-source-trail',title:'Trace Recoupment Offsets Back to the Original Payment',situation:'a current payer offset that reduces a deposit',sources:'the current remittance line, payer notice, original remittance and payment, claim version, bank trace, ledger posting, and approved disposition',risk:'a balanced net deposit can conceal a wrong claim allocation or a missing original-payment link',owner:'recoupment and accounting owner',test:'every offset component reaches its claimed original payment or stays visible as unresolved'},
 {slug:'medical-billing-retroactive-eligibility-change-queue',title:'Put Retroactive Eligibility Changes in Their Own Queue',situation:'a later eligibility response that differs from evidence used for an earlier service',sources:'the original and later responses, retrieval events, effective dates, service date, claim versions, payer messages, and decision history',risk:'a current response can rewrite the operational story without proving coverage at the earlier service date',owner:'eligibility and coordination-of-benefits owner',test:'both dated sources, the owner decision, and any authorized claim action remain linked'},
 {slug:'medical-billing-lockbox-unidentified-payment-intake',title:'Build an Intake Trail for Unidentified Lockbox Payments',situation:'bank-confirmed funds without a defensible account or remittance match',sources:'the bank trace, amount, receipt and value dates, sender detail, lockbox batch, remittance searches, candidate accounts, and exclusions',risk:'a similar amount and name can force money onto the wrong account',owner:'cash application and accounting owner',test:'the original bank event reaches an approved application or remains in a named unresolved state'},
 {slug:'medical-billing-charge-entry-lag-exception-review',title:'Measure Charge Entry Lag Without Guessing the Missing Step',situation:'encounters that have not reached the expected charge-entry state',sources:'service date, encounter status history, coding-ready event, interface receipt, charge creation time, hold reason, cancellation evidence, and owner',risk:'substituting the nearest timestamp can produce a clean but false lag measure',owner:'charge capture and coding owner',test:'each record has a reproducible interval or an explicit missing-source result'},
 {slug:'medical-billing-duplicate-payer-payment-review',title:'Treat a Possible Duplicate Payer Payment as a Hypothesis',situation:'two or more payments that appear similar in the account ledger',sources:'payer, trace, remittance and deposit dates, claim control numbers, service lines, amounts, reversal indicators, and ledger destinations',risk:'similar payments can be valid split, replacement, corrected, or repeated transactions',owner:'payment posting and accounting owner',test:'the candidate group has an evidence classification and an authorized, traceable disposition'},
 {slug:'medical-billing-clearinghouse-enrollment-expiry-alert',title:'Verify Clearinghouse Enrollment Alerts Against the Source Record',situation:'an enrollment warning on a clearinghouse transaction path',sources:'the alert text and time, payer, provider relationship, transaction type, stated date, source enrollment record, recent acknowledgments, and change history',risk:'an alert count can be mistaken for a rejection count or applied to the wrong transaction scope',owner:'clearinghouse and enrollment owner',test:'each alert has a source-supported scope, owner decision, and verified disposition'},
 {slug:'medical-billing-requested-records-delivery-receipt',title:'Keep the Delivery Receipt With Every Requested-Records Packet',situation:'a payer-requested records packet moving from preparation to delivery',sources:'the request, approved document index, claim version, minimum-necessary review, release authorization, delivery event, receipt, and later response',risk:'a complete packet can be treated as delivered even when no receipt links it to the intended claim',owner:'records release and compliance owner',test:'the request, exact packet, authority, delivery, receipt, and follow-up state remain connected'}
];
export type Sep10BlogArticle={slug:string;title:string;description:string;published:typeof published;featuredImage:string;body:string[]};
export const sep10BlogBatch:Sep10BlogArticle[]=blogSeeds.map((x,i)=>({slug:x.slug,title:x.title,published,featuredImage:blogImage,description:`A September 10 operating routine for ${x.situation}, built around source evidence and explicit decision rights.`,body:[
 `Start with the event itself: ${x.situation}. Give the work one stable, privacy-safe locator and record the intake time, source location, current state, and ${x.owner}. The row should make sense to an authorized colleague who did not see the event happen.`,
 `Gather the evidence before proposing an action: ${x.sources}. Preserve original identifiers, wording, versions, and timestamps in approved systems. Event time, system time, retrieval time, and review time answer different questions.`,
 `The practical risk is that ${x.risk}. Mark values as observed, externally reported, calculated, owner-interpreted, or unknown. When two sources disagree, keep both and route the conflict instead of choosing the more convenient value.`,
 `Define the counting unit for routine ${i+1} before work begins. Freeze the opening population, filters, cutoff, timezone, and duplicate rule. Record late arrivals and reopened items as movements so the denominator does not change silently.`,
 `Support staff may retrieve permitted records, compare fields, reproduce documented arithmetic, index files, and draft a bounded question. The ${x.owner} retains decisions that change claim content, coding, clinical meaning, credentials, money, access, submission, legal interpretation, or external communication.`,
 'Use statuses that explain the work: evidence gathered, conflict found, access blocked, awaiting owner, authorized action, or carried forward. A generic complete label is not enough unless the record shows what changed, who approved it, and where the result can be checked.',
 'Review one ordinary row and one exception with a second authorized person when both are available. Compare identifiers, sources, timing, scope, and arithmetic. Preserve disagreement because it may reveal an unstated rule or a source transformation.',
 `The close test is exact: ${x.test}. Unresolved rows need one accountable next actor and review date. Missing or inaccessible evidence stays in the count.`,
 'Keep protected information in approved tools and use the minimum necessary locator in shared trackers. An access failure belongs with the access owner; it is not permission to borrow credentials or copy sensitive records elsewhere.',
 'This September 10, 2026 guide is an administrative control. It does not make a clinical, coding, coverage, credentialing, contract, legal, privacy, or accounting determination.'
]}));
export const sep10BlogSlugs=sep10BlogBatch.map(x=>x.slug);

type ResearchSeed={slug:string;title:string;question:string;unit:string;population:string;method:string;limits:string;refs:string[]};
const researchSeeds:ResearchSeed[]=[
 {slug:'research-medical-billing-277ca-response-latency-2026',title:'277CA Response Latency Research: Where Does the Acknowledgment Trail Break?',question:'For claims in a frozen outbound batch cohort, how often can a claim-level 277CA response be linked, and where does documented latency occur?',unit:'one released claim version and its acknowledgment chain',population:'every claim version released through the selected clearinghouse path, including rejections, missing responses, resubmissions, and access-blocked records',method:'Join the batch, interchange receipt, 999 when present, 277CA, clearinghouse identifiers, payer identifiers, and claim history. Calculate intervals only where both timestamps exist. Have a second reviewer repeat a mixed sample.',limits:'Clearinghouse transformations, clock differences, retention limits, batch splits, and unavailable raw transactions may obscure the chain.',refs:['CMS transactions: https://www.cms.gov/medicare/regulations-guidance/administrative-simplification/transactions','X12 277CA: https://x12.org/products/health-care-claim-acknowledgment-277ca','CAQH CORE rules: https://www.caqh.org/core/operating-rules']},
 {slug:'research-medical-billing-enrollment-effective-date-sync-2026',title:'Enrollment Effective-Date Synchronization: A Source Comparison Study',question:'When payer enrollment evidence changes, do approved sources and local billing configuration show the same effective period?',unit:'one provider, payer, location, identifier relationship, and effective period',population:'relationships with a dated approval, termination, update, alert, rejection, or configuration change, plus unchanged comparison records and boundary-date claims',method:'Compare source wording, retrieval date, prior and current local values, claim dates, acknowledgments, and the approved change log. An independent reviewer repeats all boundary classifications.',limits:'Payer-specific rules, retroactive updates, portal history limits, timezone ambiguity, and restricted credential records limit reconstruction.',refs:['CMS provider enrollment: https://www.cms.gov/medicare/enrollment-renewal/providers-suppliers','CMS Program Integrity Manual: https://www.cms.gov/regulations-and-guidance/guidance/manuals/internet-only-manuals-ioms-items/cms019033','NPPES: https://nppes.cms.hhs.gov/']},
 {slug:'research-medical-billing-statement-suppression-aging-2026',title:'Patient Statement Suppression Aging: Are Holds Still Reviewable?',question:'Within a frozen statement-cycle population, which suppressions have current source support and which lack a reviewable disposition?',unit:'one account-level suppression active at the cycle cutoff',population:'manual and system holds active at cutoff, with post-cutoff releases and new holds reported as movements and zero-balance or access-limited records retained',method:'Compare hold type, source reason, start and review dates, configuration or account event, balance snapshot, correspondence, owner, and disposition. Test continued and released holds with a second reviewer.',limits:'Local statement rules, privacy restrictions, changing balances, system flags, correspondence gaps, and non-random cycle selection restrict generalization.',refs:['CFPB debt collection: https://www.consumerfinance.gov/consumer-tools/debt-collection/','HHS HIPAA Privacy Rule: https://www.hhs.gov/hipaa/for-professionals/privacy/index.html','CMS medical bill rights: https://www.cms.gov/medical-bill-rights']},
 {slug:'research-medical-billing-recoupment-offset-lineage-2026',title:'Recoupment Offset Lineage: Can the Current Deduction Reach Its Original Payment?',question:'For each payer offset in a frozen remittance cohort, can the deduction be traced to its stated original payment and local treatment?',unit:'one current offset component and its claimed original-payment relationship',population:'every offset component in selected remittances, including multi-claim offsets, missing notices, disputed links, reversals, and unapplied amounts',method:'Trace the current remittance to notice references, original remittance lines, claim versions, deposits, postings, and approved dispositions. Recompute gross, offset, and net values. A second reviewer reproduces a stratified sample.',limits:'Payer practices, truncated text, combined deposits, local accounting policy, inaccessible notices, and historical conversions may prevent reconstruction.',refs:['CMS Financial Management Manual: https://www.cms.gov/regulations-and-guidance/guidance/manuals/internet-only-manuals-ioms-items/cms019017','CMS ERA: https://www.cms.gov/medicare/coding-billing/electronic-billing/electronic-remittance-advice','X12 835: https://x12.org/products/health-care-claim-paymentadvice-835']},
 {slug:'research-medical-billing-attachment-claim-association-2026',title:'Attachment-to-Claim Association: A Transaction Evidence Study',question:'Can each delivered attachment packet be associated with the payer request, intended claim version, authorization, transmission, and receipt?',unit:'one delivered packet version for one payer request and claim relationship',population:'packets delivered in the window, returned or repeated deliveries, missing-receipt records, and ordinary receipt comparisons, with unavailable documents retained',method:'Compare request references, claim and attachment control numbers, service periods, document versions, approval, delivery channel, transaction time, receipt, and later response. A second reviewer repeats the matching.',limits:'Portal retention, proprietary identifiers, protected information, manual uploads, payer rules, and incomplete response history can limit linkage.',refs:['CMS clinical attachments: https://www.cms.gov/priorities/key-initiatives/burden-reduction/attachments','HHS HIPAA Privacy Rule: https://www.hhs.gov/hipaa/for-professionals/privacy/index.html','X12 278: https://x12.org/products/health-care-services-review-information-278']}
];
export type Sep10ResearchArticle={slug:string;title:string;excerpt:string;published:typeof published;datePublished:typeof published;updated:typeof published;featuredImage:string;body:string[]};
export const sep10ResearchBatch:Sep10ResearchArticle[]=researchSeeds.map(x=>({slug:x.slug,title:x.title,excerpt:`A September 10 evidence study asking: ${x.question}`,published,datePublished:published,updated:published,featuredImage:researchImage,body:[
 `Research question: ${x.question}`,
 `Scope: This September 10, 2026 study concerns administrative evidence in outsourced medical billing. The unit of analysis is ${x.unit}. It excludes clinical care, staff merit, legal compliance, contract entitlement, and payer decision correctness.`,
 `Population and observation window: Include ${x.population}. Freeze the start, end, cutoff, timezone, source query, filters, extraction time, duplicate rule, and exclusions before review.`,
 `Methodology: ${x.method} Preserve source wording, stable identifiers, event and retrieval dates, exclusions, unknowns, reopened items, and access failures. Label statements observed, externally reported, calculated, owner-interpreted, or unknown.`,
 'Analysis: Report source-confirmed, conflicting, missing, access-blocked, superseded, interpretation-required, and unresolved results. Publish raw numerators and denominators with every rate. Keep sequence distinct from cause.',
 'Inference boundaries: Findings apply only to this frozen population, these systems, and this period. Association, timing, amount agreement, and missing evidence do not establish causation, fault, authorization, or future payer outcomes. Another setting requires replication.',
 'Role boundary: Support staff may retrieve approved records, preserve chronology, compare fields, reproduce arithmetic, and prepare a neutral exception. Qualified owners retain coding, clinical, credentialing, privacy, contract, accounting, submission, refund, write-off, appeal, and patient-communication decisions.',
 `Limitations: ${x.limits} Interface changes, incomplete history, access restrictions, local policy, and reviewer disagreement remain visible in the report.`,
 'Conclusion: The design tests whether the administrative evidence chain is reproducible and identifies exactly where it stops. It cannot make a clinical, legal, financial, or payer determination.',
 'References:', ...x.refs.map(r=>`Primary source reviewed September 10, 2026: ${r}`)
]}));
