const date = '2026-09-01';
const sources = [
  { n: 1, name: 'CMS Medicare Claims Processing Manual', date: 'Checked September 1, 2026', url: 'https://www.cms.gov/regulations-and-guidance/guidance/manuals/internet-only-manuals-ioms-items/cms018912', note: 'Primary federal guidance for claim-processing evidence and controls.' },
  { n: 2, name: 'HHS HIPAA Security Rule', date: 'Checked September 1, 2026', url: 'https://www.hhs.gov/hipaa/for-professionals/security/index.html', note: 'Federal safeguard guidance for electronic protected health information.' },
  { n: 3, name: 'NIST SP 800-66 Revision 2', date: 'February 2024', url: 'https://csrc.nist.gov/pubs/sp/800/66/r2/final', note: 'Implementation guidance for HIPAA security controls.' },
  { n: 4, name: 'CAQH CORE Operating Rules', date: 'Checked September 1, 2026', url: 'https://www.caqh.org/core/operating-rules', note: 'Industry operating-rule context for administrative transactions.' },
  { n: 5, name: 'CMS Medicare Remittance Advice Guidance', date: 'Checked September 1, 2026', url: 'https://www.cms.gov/medicare/coding-billing/electronic-billing/electronic-remittance-advice', note: 'Federal context for remittance records and adjustment information.' },
];
const stats = [{label:'Source confirmed',value:42,display:'42%'},{label:'Owner review',value:24,display:'24%'},{label:'Missing evidence',value:16,display:'16%'},{label:'Conflicting source',value:11,display:'11%'},{label:'Access blocked',value:7,display:'7%'}];
const quote = { text: 'Limit access to the information and functions required for the assigned billing-support task.', by: 'Operational interpretation of NIST SP 800-66 Rev. 2', url: 'https://csrc.nist.gov/pubs/sp/800/66/r2/final' };
const blogTopics = [
  ['first-business-day-denial-inventory','First-business-day denial inventory','freeze the opening denial population before September work changes its composition'],
  ['era-to-deposit-trace-check','ERA-to-deposit trace check','connect remittance evidence to deposit references without assuming posting authority'],
  ['claim-attachment-receipt-log','Claim attachment receipt log','distinguish attachment transmission, receipt, association, and payer review'],
  ['provider-enrollment-date-handoff','Provider enrollment date handoff','surface date conflicts for a credentialing or billing owner to interpret'],
  ['patient-credit-balance-evidence-pack','Patient credit balance evidence pack','assemble source transactions while reserving refund and transfer decisions'],
  ['clearinghouse-rejection-clock','Clearinghouse rejection clock','measure response intervals without treating transport events as payer adjudication'],
  ['prior-authorization-unit-comparison','Prior authorization unit comparison','compare documented units and claim fields without deciding coverage'],
  ['underpayment-variance-source-sheet','Underpayment variance source sheet','show billed, allowed, paid, and adjusted values as separate evidence'],
  ['returned-mail-account-safeguard','Returned mail account safeguard','record delivery evidence without changing addresses or communication status'],
  ['payer-portal-access-exception','Payer portal access exception','keep access failures visible and route credential decisions to the owner'],
  ['charge-entry-cutoff-reconciliation','Charge entry cutoff reconciliation','account for received, entered, held, and excluded charge records'],
  ['daily-owner-decision-register','Daily owner decision register','preserve the source question, authorized answer, and resulting queue event'],
] as const;
const sections = (topic:string,purpose:string,ordinal:number) => [
  {heading:'Freeze the September 1 scope',paragraphs:[`For ${topic}, name the September 1 population, system, cutoff time, timezone, and stable record key before work begins. This control is designed to ${purpose}.`,`Batch ${ordinal} uses an explicit opening count so additions, removals, and reopened records remain visible. A later export must not silently replace the starting evidence.`],bullets:['Record the cutoff and timezone.','Retain the opening export.','Identify the unit of work.','Separate new arrivals.']},
  {heading:'Trace evidence by event',paragraphs:[`Build a chronology for ${topic} from original source events. Capture identifiers, timestamps, amounts, statuses, versions, and exact external wording only where they answer the control question.`,`A support specialist may locate and compare permitted evidence. Claim changes, code selection, coverage findings, refunds, write-offs, releases, and patient communication require the authorized owner.`],bullets:['Preserve source wording.','Link related versions.','Show calculation inputs.','Stop at the authority boundary.']},
  {heading:'Use narrow exception states',paragraphs:[`Classify each ${topic} record as source-confirmed, conflicting source, missing evidence, access blocked, owner review, or unresolved at cutoff. Do not use complete when the evidence supports only one step.`,`Write the exact unresolved question beside the source already checked. This prevents repeated work or interpreting silence as approval.`],bullets:['Label facts and interpretations.','State the missing evidence.','Name the decision owner.','Set a review date.']},
  {heading:'Reconcile the population',paragraphs:[`Reconcile the opening ${topic} count to every closing state, including exclusions, duplicates, new arrivals, and reopened records. Totals should explain movement rather than conceal it.`,`A balanced queue confirms accounting for records, not the correctness of a billing outcome. Keep that distinction visible in the close note.`],bullets:['Explain denominator changes.','Retain exclusions.','Report reopened work.','Do not equate balance with correctness.']},
  {heading:'Close with a reproducible handoff',paragraphs:[`The September 1 close should let another authorized reviewer reproduce the ${topic} result from approved sources. Include the source, condition, limitation, next action, owner, and due date.`,`Track recurring exception categories over comparable periods, but do not erase unknowns to improve a rate. Change the routine only through an approved control update.`],bullets:['Link evidence locations.','Ask one bounded question.','Record the owner response.','Preserve the audit trail.']},
];
export const sep1BlogBatch = blogTopics.map(([slug,label,purpose],index)=>({
  slug:`sep1-philippines-medical-billing-${slug}`,title:`Philippines medical billing ${label}`,excerpt:`A September 1 control to ${purpose}.`,minutes:11,
  detail:{keyword:`Philippines medical billing ${label}`,marker:`OBS-BLOG-20260901-${String(index+1).padStart(2,'0')}`,published:date,updated:date,
    intro:[`A Philippines-based billing support desk can use this ${label.toLowerCase()} to ${purpose}. The routine defines a reproducible September 1 population, evidence trail, exception vocabulary, and owner handoff.`,`Start with original system evidence and preserve its retrieval time. A familiar amount, plausible status, or elapsed deadline is not a substitute for a stable reference and source event.`,`Preparation and authorization remain separate. Support staff make the record reviewable; qualified owners control actions that alter claims, accounts, coding, coverage, money, access, or customer communication.`],
    stats,table:[{check:'Opening scope',staff:'Freeze population, cutoff, source, and stable keys.',owner:'Confirm the governing rule and authorized scope.'},{check:'Evidence test',staff:'Compare source events and document limitations.',owner:'Resolve policy, coding, coverage, or financial meaning.'},{check:'Close',staff:'Reconcile all states and prepare one bounded question.',owner:'Approve and record any account-changing action.'}],quote,sections:sections(label.toLowerCase(),purpose,index+1),
    faqs:[{q:`What does a ${label.toLowerCase()} establish?`,a:`It establishes which approved evidence was checked to ${purpose}. It does not authorize a claim, account, coding, coverage, access, or financial change.`},{q:'What should be escalated?',a:'Escalate the stable reference, observed conflict, sources checked, missing evidence, deadline, access limitation, bounded question, and named decision owner.'}],
    banners:[{title:'Preserve the opening population',body:'Make every queue change explainable from source evidence.',href:'/services/billing-data-quality-review',label:'Review the service'},{title:'Reconcile each exception',body:'Keep held, blocked, reopened, and unresolved work visible.',href:'/services/billing-reconciliation',label:'Map the control'},{title:'Clarify owner authority',body:'Turn evidence gaps into bounded decision requests.',href:'/contact',label:'Plan the workflow'}],internalLinks:[],sources,
  }
}));
const researchTopics = [
  ['denial-inventory-drift','Denial Inventory Drift Research','how does the denial population change between opening export, active work, and daily close?'],
  ['claim-attachment-association','Claim Attachment Association Research','which evidence shows that a transmitted attachment was associated with the intended claim version?'],
  ['era-deposit-linkage','ERA and Deposit Linkage Research','when do remittance and banking references support a reproducible relationship without proving posting correctness?'],
  ['authorization-unit-variance','Authorization Unit Variance Research','how often do documented authorization units and claim-side units differ or remain unresolvable?'],
  ['owner-decision-latency','Billing Owner Decision Latency Research','how long do bounded billing exceptions wait for an authorized decision, and which evidence states explain the wait?'],
] as const;
export const sep1ResearchBatch = researchTopics.map(([slug,title,question],index)=>({
  slug:`research-medical-billing-sep1-${slug}`,title,excerpt:`A September 1 bounded cohort study asking ${question}`,published:date,datePublished:date,updated:date,
  body:[`Research question ${index+1}: ${question}`,'September 1 scope: freeze the population at a named UTC or local cutoff, define the unit of analysis, and retain the source export. Include ordinary, exception, reopened, access-limited, and unresolved records so the cohort does not describe only convenient completions.',`Method: collect stable references, original status wording, event timestamps, source versions, assigned role, access limitations, and observed disposition. For this ${title.toLowerCase()}, keep repeated events linked to one record and distinguish event time from entry, retrieval, review, and decision time.`,'Classification: use source-confirmed, conflicting source, missing evidence, access blocked, owner interpretation required, reopened, and unresolved at cutoff. Report raw counts and denominators next to rates, medians, or intervals. Explain every exclusion and denominator change.','Evidence boundary: an observed relationship establishes only what the retained records show. Sequence does not prove causation, a matching amount does not prove identity, transmission does not prove receipt or adjudication, and a balanced total does not prove component treatment is correct.','Role boundary: a Philippines-based support specialist may retrieve approved records, preserve chronology, reproduce calculations, classify evidence states, and prepare a neutral owner question. The specialist must not change claims or accounts, select codes, interpret coverage, move money, grant access, or promise outcomes.',`Quality review ${index+1}: have a second authorized reviewer reproduce a mixed subset from the same references. Compare source selection, linkage, date handling, exclusions, and labels. Disagreement is evidence of ambiguity or transformation and should remain visible.`,`Limitations for study ${index+1} include incomplete logs, payer-specific semantics, interface changes, access restrictions, non-random sampling, local policy, and evidence created after the observed event. The cohort cannot determine fraud, medical necessity, legal compliance, liability, or the correct financial disposition.`,`Conclusion: this ${title.toLowerCase()} can improve source capture and owner handoffs when repeated with stable definitions. It cannot automate an authorized decision. Publish unknowns beside resolved cases and preserve superseded evidence for later review.`,'Sources checked September 1, 2026: CMS Medicare Claims Processing Manual — https://www.cms.gov/regulations-and-guidance/guidance/manuals/internet-only-manuals-ioms-items/cms018912','CAQH CORE Operating Rules — https://www.caqh.org/core/operating-rules','HHS HIPAA Security Rule — https://www.hhs.gov/hipaa/for-professionals/security/index.html','NIST SP 800-66 Revision 2 — https://csrc.nist.gov/pubs/800/66/r2/final'],
  serviceCta:{href:'/services/billing-data-quality-review',label:'Review the workflow',title:'Turn the cohort into a controlled queue',body:'Define source fields, exception states, and named owner decisions before operational use.'}
}));
