import { buildDecisionResearchBody, type ResearchSeed, type ResearchSource } from './sep22b-research';

const published = '2026-09-23' as const;
const checked = 'September 23, 2026';
const featuredImage = '/aug20-research-heroes/research-medical-billing-denial-response-evidence.png';
const cmsClaims: ResearchSource = { title: 'Medicare Claims Processing Manual', publisher: 'Centers for Medicare & Medicaid Services', url: 'https://www.cms.gov/regulations-and-guidance/guidance/manuals/internet-only-manuals-ioms-items/cms018912', use: 'primary Medicare claims-processing context while current payer-specific instructions still control each case' };
const cmsRemit: ResearchSource = { title: 'Health Care Payment and Remittance Advice', publisher: 'Centers for Medicare & Medicaid Services', url: 'https://www.cms.gov/medicare/coding-billing/electronic-billing/health-care-payment-remittance-advice', use: 'claim-, line-, and provider-level adjustment structure and ERA or SPR evidence' };
const cmsAppeals: ResearchSource = { title: 'Original Medicare Appeals', publisher: 'Centers for Medicare & Medicaid Services', url: 'https://www.cms.gov/medicare/appeals-grievances/original-medicare-appeals', use: 'Medicare appeal stages without generalizing deadlines to other payers' };
const cmsNcci: ResearchSource = { title: 'Medicare National Correct Coding Initiative Edits', publisher: 'Centers for Medicare & Medicaid Services', url: 'https://www.cms.gov/medicare/coding-billing/national-correct-coding-initiative-ncci-edits', use: 'current Medicare edit resources for qualified coding-owner review' };
const hhs: ResearchSource = { title: 'Security Rule Guidance Material', publisher: 'U.S. Department of Health and Human Services', url: 'https://www.hhs.gov/hipaa/for-professionals/security/guidance/index.html', use: 'safeguard context for protected billing evidence' };
const nist: ResearchSource = { title: 'Security and Privacy Controls for Information Systems and Organizations, SP 800-53 Revision 5', publisher: 'National Institute of Standards and Technology', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', use: 'least privilege, audit records, information integrity, and controlled change' };

const seeds: ResearchSeed[] = [
  {
    slug: 'research-medical-billing-denial-to-appeal-deadline-lineage-2026', topic: 'denial to appeal deadline lineage', title: 'Denial-to-Appeal Deadline Lineage Research: Which Date Starts the Clock?', excerpt: 'A source-led study connecting denial notices, receipt evidence, payer instructions, appeal stages, owner decisions, and submission proof.',
    question: 'For each denial selected for appeal review, can the team reproduce the controlling deadline candidate from the original notice and current payer instruction without substituting a queue date or memory?', decision: 'whether denial support can maintain a reliable deadline register while a qualified owner retains responsibility for interpreting rules and authorizing the appeal', unit: 'one payer denial at one appeal stage linked to one notice version, one deadline calculation, and one disposition', population: 'all denials entering or remaining in the window, including corrected notices, portal messages, mailed notices, multiple lines, reopened cases, returned submissions, inaccessible records, and date conflicts', evidence: 'payer and plan; claim and line reference; notice type and version; notice and received dates; appeal stage; exact deadline wording; checked payer resource; calculation inputs; timezone; owner interpretation; submission channel; confirmation; rejection; and supersession history', states: 'notice verified, instruction verified, date conflict, receipt unknown, stage unclear, calculation reproduced, owner interpretation required, ready, submitted with proof, returned, superseded, inaccessible, expired candidate, and unresolved', tests: 'trace each date to notice wording and a checked payer source; independently recalculate boundary cases; distinguish calendar and business days; test weekends only when required; compare notice, receipt, queue, approval, and submission times; preserve rejected candidates; and route rule conflicts to an authorized reviewer', interpretation: 'A queue due date is not proof of a payer deadline. A timely-looking submission is not proved without channel evidence, and an expired candidate does not establish that no exception or later stage exists.', limitations: 'Payer, plan, jurisdiction, stage, delivery method, contract, emergency rules, portal behavior, and corrected notices can change the rule. This study cannot provide legal advice, determine merits, extend a deadline, or authorize submission.', service: '/services/dispute-documentation', serviceLabel: 'Review dispute-documentation support', sources: [cmsAppeals, cmsClaims, hhs],
  },
  {
    slug: 'research-medical-billing-claim-attachment-transmission-lineage-2026', topic: 'claim attachment transmission lineage', title: 'Claim Attachment Transmission Research: Did the Requested Record Reach the Right Claim?', excerpt: 'A transmission-lineage design linking payer requests, approved records, claim identifiers, channels, acknowledgments, and follow-up.',
    question: 'For every claim attachment marked sent, can a reviewer connect the payer request to the authorized record set, correct claim, transmission event, acknowledgment, and later payer status?', decision: 'whether documentation follow-up is controlled enough to delegate without letting support staff choose clinical records or infer payer acceptance', unit: 'one payer attachment request linked to one claim, one approved package version, and one transmission attempt', population: 'all requested, prepared, sent, failed, returned, replaced, cancelled, and open attachment events, including multi-claim packages, duplicates, portal uploads, faxes, inaccessible acknowledgments, and post-cutoff responses', evidence: 'payer request; claim and line identifiers; requested record; approved source locator; approving owner; package manifest and version; minimum-necessary review; destination; channel; transmission time and actor; confirmation; failure response; payer status; follow-up; and supersession link', states: 'request verified, records awaiting owner, package approved, identifier conflict, destination conflict, ready, transmitted, acknowledged, failed, returned, replaced, receipt unconfirmed, inaccessible, and unresolved', tests: 'match request identifiers before packaging; compare the manifest with approved sources; verify the destination; reconcile each attempt to a timestamped response; test multi-claim and replacement packages separately; review disclosure boundaries; and sample acknowledgments back to exact package versions', interpretation: 'A successful upload or fax proves transmission to a destination, not payer acceptance, claim association, clinical sufficiency, or favorable adjudication.', limitations: 'Payer portals, fax systems, indexing, protected information, record availability, attachment standards, and delayed status updates constrain evidence. The method cannot select clinical content, make a privacy determination, certify medical necessity, or authorize submission.', service: '/services/collections-follow-up', serviceLabel: 'Review documentation follow-up support', sources: [cmsClaims, hhs, nist],
  },
  {
    slug: 'research-medical-billing-charge-capture-lag-cohort-2026', topic: 'charge capture lag cohort', title: 'Charge Capture Lag Research: Where Does Billable Work Wait?', excerpt: 'A cohort study separating service evidence, charge readiness, coding questions, interface movement, claim preparation, and excluded time.',
    question: 'Across a frozen service cohort, which dated event intervals explain the time from documented service to claim-ready charge, and which intervals remain unknown?', decision: 'whether charge-entry support needs better source access, interface monitoring, capacity, or qualified-owner response rather than a misleading single target', unit: 'one included service or encounter linked to one charge version and one claim-readiness disposition', population: 'all services meeting the written inclusion rule, including zero-charge outcomes, cancellations, late documentation, interface failures, coding queries, duplicates, corrections, inaccessible records, and unresolved items', evidence: 'service identifier; service times; documentation completion; source charge event; interface receipt; edit result; query times; charge version; claim-ready time; exclusion reason and owner; timezone; system clocks; and post-cutoff movement', states: 'service observed, documentation pending, source charge absent, interface pending, edit exception, coding review, duplicate candidate, charge prepared, owner review, claim ready, supported exclusion, cancelled, inaccessible, and unresolved', tests: 'freeze the cohort from the service source; reconcile each service to a disposition; calculate intervals only from present source events; compare clocks and date-only fields; report medians and tails with denominators; inspect negative intervals; and independently reproduce sampled timelines', interpretation: 'Elapsed time identifies where evidence appears to wait; it does not prove fault, billability, coding correctness, or avoidable delay. Missing records can represent exclusions, interface loss, owner work, or incomplete observation.', limitations: 'Service definitions, late entries, clocks, clinical documentation, interfaces, payer edits, coding workload, cancellations, and non-random access can bias the cohort. This cannot determine clinical completeness, codes, billability, staffing, or a universal benchmark.', service: '/services/billing-data-quality-review', serviceLabel: 'Review billing data-quality support', sources: [cmsClaims, cmsNcci, nist],
  },
  {
    slug: 'research-medical-billing-era-posting-exception-reproducibility-2026', topic: 'ERA posting exception reproducibility', title: 'ERA Posting Exception Research: Can a Second Reviewer Reproduce the Proposed Entry?', excerpt: 'A line-level study of remittance codes, amounts, claim links, posting rules, exceptions, approvals, and reconciliation.',
    question: 'For each ERA posting exception, can an independent reviewer reproduce the proposed local entry from the same remittance lines, claim record, approved rule, and reconciliation evidence?', decision: 'whether payment-posting support has enough evidence and rule clarity for routine preparation while financial decisions remain with authorized owners', unit: 'one ERA claim or service line and related adjustments linked to one proposed posting and one batch reconciliation', population: 'all ERA lines routed to exception, including reversals, takebacks, zero-pay claims, multiple adjustments, provider-level balances, unmatched claims, split payments, duplicate candidates, missing text, and unresolved items', evidence: 'ERA and batch identifier; claim and line reference; paid amount; group code, CARC, RARC, and PLB references; claim values; deposit trace; mapping version; proposed entry; prior posting; exception; preparer; reviewer; owner decision; system result; and reconciliation movement', states: 'source linked, deposit linked, rule reproduced, mapping missing, code conflict, amount conflict, claim unmatched, provider-level adjustment, reversal candidate, duplicate candidate, owner decision required, approved, posted, rejected, held, and unresolved', tests: 'reconcile ERA and deposit totals while retaining line detail; reproduce entries from preserved mappings; test code combinations; separate claim-, line-, and provider-level adjustments; inspect reversals; compare proposed and posted results; and independently review balance-changing exceptions', interpretation: 'A balanced batch can conceal line-level misapplication. Standard codes explain reported adjudication but do not by themselves prove the correct local ledger treatment or patient balance.', limitations: 'Payer usage, incomplete fields, mapping changes, accounting policy, claim history, deposits, reversals, and aggregation can prevent a definitive result. The study cannot authorize refunds, transfers, write-offs, patient responsibility, or accounting entries.', service: '/services/payment-posting', serviceLabel: 'Review payment-posting support', sources: [cmsRemit, cmsClaims, nist],
  },
  {
    slug: 'research-medical-billing-corrected-claim-version-lineage-2026', topic: 'corrected claim version lineage', title: 'Corrected Claim Version Research: What Changed, Who Approved It, and What Was Replaced?', excerpt: 'A version-control study connecting original submissions, payer responses, source corrections, approvals, replacement indicators, and acknowledgments.',
    question: 'For every corrected or replacement claim, can a reviewer reconstruct the original version, exact field changes, supporting source, qualified approval, resubmission relationship, and payer acknowledgment?', decision: 'whether corrected-claim support can prepare traceable change packets without silently making coding, clinical, enrollment, or payer-policy decisions', unit: 'one claim version connected to its predecessor, change set, evidence, approval, transmission, and payer response', population: 'all claims designated corrected, replacement, void, adjustment, or resubmission, including rejected attempts, multiple corrections, partial changes, payer-requested updates, duplicate candidates, missing predecessors, and unresolved chains', evidence: 'claim and payer identifiers; version; predecessor and successor links; original and changed values; reason; payer response; source locator; qualified owner; approval scope and time; replacement indicator; transmission; acknowledgment; adjudication response; and supersession status', states: 'lineage complete, predecessor missing, change set reproduced, source conflict, coding review required, enrollment review required, payer instruction unclear, approved, transmitted, rejected, acknowledged, adjudicated, voided, duplicate candidate, superseded, and unresolved', tests: 'compare versions field by field; preserve unchanged context; trace changes to source and approval; verify replacement relationships; distinguish transport rejection from adjudication; inspect multi-version chains; reconcile status to acknowledgments; and independently reproduce high-risk corrections', interpretation: 'A payer acknowledgment proves only what its response states. A changed field is evidence of a change, not proof that the correction was authorized. Report lineage, source, approval, transmission, and response separately.', limitations: 'Payer rules, clearinghouse transformations, identifier changes, incomplete archives, clinical documentation, coding guidance, enrollment records, and delayed responses may break the chain. This cannot select codes, determine medical necessity, certify enrollment, or authorize resubmission.', service: '/services/billing-data-quality-review', serviceLabel: 'Review billing data-quality support', sources: [cmsClaims, cmsNcci, hhs],
  },
];

export const sep23ResearchBatch = seeds.map((x) => ({
  slug: x.slug, title: x.title, excerpt: x.excerpt, published, datePublished: published, updated: published,
  featuredImage, body: buildDecisionResearchBody(x), serviceCta: { href: x.service, label: x.serviceLabel, title: 'Turn this research design into a controlled daily billing routine', body: 'Define the population, evidence, stopping points, review owner, and approval boundary before assigning volume.' },
}));
export const sep23ResearchTopics = seeds.map(({ slug, topic, sources }) => ({ slug, topic, sources }));
