import { buildDecisionResearchBody, type ResearchSeed, type ResearchSource } from './sep22b-research';

const published = '2026-09-28' as const;
const checked = 'September 28, 2026';
const featuredImage = '/aug20-research-heroes/research-medical-billing-remittance-batch-reconciliation.png';

const greenBook: ResearchSource = { title: 'Standards for Internal Control in the Federal Government: 2025 Revision', publisher: 'U.S. Government Accountability Office', url: 'https://www.gao.gov/greenbook', use: 'quality information, documented control activities, segregation of duties, and monitoring' };
const nist: ResearchSource = { title: 'Security and Privacy Controls for Information Systems and Organizations, SP 800-53 Revision 5', publisher: 'National Institute of Standards and Technology', url: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final', use: 'audit records, least privilege, controlled change, information integrity, and contingency processing' };
const ftc: ResearchSource = { title: 'Protecting Personal Information: A Guide for Business', publisher: 'U.S. Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business', use: 'data inventory, limited access, secure handling, service-provider oversight, and disposal' };
const fasb: ResearchSource = { title: 'Revenue Recognition: ASU 2014-09, Revenue from Contracts with Customers (Topic 606)', publisher: 'Financial Accounting Standards Board', url: 'https://fasb.org/projects/recently-completed-projects/revenue-recognition-summary', use: 'authoritative context for revenue judgments that remain with qualified accounting owners' };
const cisa: ResearchSource = { title: 'Use Logging on Business Systems', publisher: 'Cybersecurity and Infrastructure Security Agency', url: 'https://www.cisa.gov/audiences/small-and-medium-businesses/secure-your-business/use-logging-on-business-systems', use: 'useful event records, centralized logging, protected log access, and retention' };

const seeds: ResearchSeed[] = [
  {
    slug: 'research-outsourced-billing-invoice-delivery-acknowledgment-integrity-2026', topic: 'invoice delivery acknowledgment integrity',
    title: 'Invoice Delivery Acknowledgment Research: Was the Released Invoice Actually Received?',
    excerpt: 'An event-lineage study separating invoice release, transport acceptance, destination delivery, rejection, customer access, and follow-up.',
    question: 'For every invoice released in a bounded cycle, can a reviewer trace the exact version from release through the approved delivery channel to a supported delivered, rejected, pending, or unresolved state?',
    decision: 'whether invoice-delivery monitoring can be delegated as evidence collection and exception routing without allowing support staff to declare legal receipt or improvise customer communications',
    unit: 'one released invoice version sent to one approved destination through one declared channel, including every retry and terminal response',
    population: 'all invoice versions released during the window, including email, portal, electronic interchange, postal handoff, batch delivery, retries, corrected invoices, duplicate-looking sends, suppressed messages, invalid destinations, delayed responses, inaccessible logs, and open exceptions',
    evidence: 'invoice and immutable version; release approval and time; approved destination source and version; delivery channel; message or batch identifier; dispatch event; provider acceptance; destination response; rejection code and text; portal publication; retry chain; customer contact restriction; correction or cancellation; preparer; reviewer; next action; and closure evidence',
    states: 'released not dispatched, dispatched, provider accepted, destination delivered, portal available, rejected transient, rejected permanent, destination conflict, suppressed, retry held, retry completed, corrected version supersedes, customer confirmation observed, owner interpretation required, inaccessible, and unresolved',
    tests: 'trace released versions forward to delivery events and delivery events backward to the invoice; compare destination values with their approved source version; separate provider acceptance from destination delivery; preserve rejection text; link retries without double-counting; inspect corrections and cancellations; reconcile batch counts; and independently reproduce every claimed terminal state',
    interpretation: 'A transport provider acceptance is not proof that the customer read or legally received an invoice. An open or click event can be incomplete or privacy-sensitive evidence. Report what each system observed, the channel limitation, and the unresolved next action without converting a technical event into a legal conclusion.',
    limitations: 'Channel-provider semantics, customer mail controls, portal authentication, shared addresses, privacy features, postal evidence, retention periods, integration delays, and contract terms constrain attribution. The study cannot decide legal notice, customer assent, collectibility, revenue treatment, or whether collection activity should begin.',
    service: '/services/invoice-preparation', serviceLabel: 'Review invoice-preparation support', sources: [greenBook, nist, cisa, ftc],
  },
  {
    slug: 'research-outsourced-billing-subscription-retry-authorization-state-2026', topic: 'subscription payment retry authorization state',
    title: 'Subscription Retry Research: Was Each Attempt Allowed by the Current Account State?',
    excerpt: 'A state-attempt cohort linking failed payments, approved retry rules, pauses, cancellations, restrictions, attempt results, and owner decisions.',
    question: 'For every automated or manual subscription payment retry, can the team reconstruct the account state, approved retry rule, restriction check, attempt event, response, and next disposition that existed at that time?',
    decision: 'whether subscription-billing support can monitor retry evidence and prepare exceptions while commercial, payment, compliance, and customer owners retain authority over attempts and communications',
    unit: 'one payment attempt linked to one subscription version, one approved retry-policy version, and one processor response',
    population: 'all initial and repeated payment attempts in the selected cycle, including successful, failed, blocked, paused, cancelled, disputed, expired-method, processor-error, manually initiated, duplicate candidate, migrated, test, inaccessible, and unresolved attempts',
    evidence: 'subscription and account locator; plan version; billing event; amount and currency; prior attempt chain; approved retry-policy version and effective time; pause or cancellation state; communication or contact restriction; payment-token locator rather than sensitive credentials; initiator; attempt time and timezone; processor identifier; exact response; next scheduled action; override approval; reviewer; and final disposition',
    states: 'initial attempt, policy-eligible retry, policy-ineligible candidate, paused, cancelled, restriction present, timing conflict, amount conflict, processor declined, processor error, confirmation uncertain, duplicate candidate, override supported, override unsupported, succeeded, stopped, inaccessible, and unresolved',
    tests: 'order account-state and policy versions before each attempt; compare scheduled and actual timestamps; verify amount and currency continuity; distinguish processor decline from transport failure; identify attempts after pause or cancellation; link manual overrides to approval; test duplicate-looking processor identifiers; reconcile attempt counts by subscription; and independently review every eligibility exception',
    interpretation: 'A processor response proves only the observed result for the submitted attempt. It does not establish that the retry was contractually permitted, that a decline reason is complete, or that another attempt should occur. Eligibility, execution, response, customer communication, and owner decision are separate findings.',
    limitations: 'Processor response semantics, tokenized data, retry products, contract terms, network rules, consumer protections, jurisdiction, timezones, migrations, delayed cancellation events, and incomplete logs constrain reconstruction. The method cannot authorize a charge, select a retry strategy, interpret legal requirements, waive an amount, or approve customer messaging.',
    service: '/services/subscription-billing-support', serviceLabel: 'Review subscription-billing support', sources: [greenBook, nist, ftc, cisa],
  },
  {
    slug: 'research-outsourced-billing-usage-late-arrival-cutoff-cohort-2026', topic: 'usage event late-arrival cutoff cohort',
    title: 'Late Usage Event Research: Which Billing Cycle Should Receive the Evidence?',
    excerpt: 'A cohort study of event time, ingestion time, correction lineage, frozen cutoffs, invoice disposition, and owner-approved carryforward.',
    question: 'For usage events arriving after a declared billing cutoff, can a reviewer determine which source period they describe, why they arrived late, how they were classified, and what approved disposition followed without silently moving dates?',
    decision: 'whether usage-billing administration has a reproducible late-arrival queue while contract, customer, accounting, and release decisions remain with authorized owners',
    unit: 'one source usage event or declared source aggregate received after the frozen cutoff and linked to one billing disposition',
    population: 'all events first ingested after cutoff that relate or may relate to the closed period, including delayed source exports, clock drift, timezone boundaries, corrections, reversals, duplicates, resends, aggregate replacements, manual uploads, inaccessible raw events, and items still unresolved at the next cutoff',
    evidence: 'source and stable event identifier; customer and service mapping; original event timestamp and timezone; source-created timestamp; extraction and ingestion times; cutoff definition; file or API version and hash; correction or supersession link; quantity and unit; prior billed state; candidate cycle; contract-rule locator; owner question; approved disposition; invoice line; preparer; reviewer; and later reconciliation',
    states: 'late source creation, late extraction, late transport, late ingestion, timezone ambiguity, clock conflict, correction, reversal, duplicate candidate, aggregate replacement, prior cycle candidate, current cycle candidate, hold, owner interpretation required, approved carryforward, excluded with evidence, inaccessible, and unresolved',
    tests: 'preserve original timestamps and timezones; compare event, source-created, extraction, and ingestion times; freeze each cutoff definition; deduplicate by lineage rather than amount; trace corrections to originals; compare late events with prior invoice lines; reconcile quantities across opening, late, billed, excluded, and closing states; inspect boundary cases; and independently reproduce cycle classifications',
    interpretation: 'Late ingestion does not prove late service or source error, and an event timestamp does not alone decide its billable period. The evidence can locate delay layers and quantify dispositions, while contract interpretation, customer treatment, accounting cutoff, and invoice release remain owner judgments.',
    limitations: 'Source clocks, timezone conversion, offline devices, aggregation, mutable exports, contract language, correction practices, incomplete raw events, migration history, and close policy limit classification. The study cannot determine contractual entitlement, price, tax, accounting period, revenue recognition, or whether a customer should be billed.',
    service: '/services/usage-billing-administration', serviceLabel: 'Review usage-billing administration support', sources: [greenBook, nist, cisa, fasb],
  },
  {
    slug: 'research-outsourced-billing-credit-memo-downstream-propagation-2026', topic: 'credit memo downstream propagation',
    title: 'Credit Memo Propagation Research: Did the Approved Change Reach Every Dependent Record?',
    excerpt: 'A cross-system study connecting approved credit versions to invoice balances, statements, aging, collections, payment application, and close handoffs.',
    question: 'After a credit memo is approved and posted, can every dependent billing record be traced to the same credit version and can every mismatch remain visible until an authorized owner resolves it?',
    decision: 'whether credit-memo administration needs a controlled propagation check that support staff can prepare without deciding accounting, tax, refund, collection, or customer outcomes',
    unit: 'one approved credit memo version linked to each declared downstream system, report, queue, or customer-facing artifact it is expected to affect',
    population: 'all credit memos approved or posted during the window, including partial credits, tax components, multi-invoice credits, unapplied credits, reversed credits, corrected versions, refund candidates, disputed items, closed-period postings, interface failures, inaccessible systems, and unresolved propagation differences',
    evidence: 'credit memo and immutable version; original invoice and lines; request and reason source; approval scope and time; amount, tax, and currency components; posting event; customer balance; invoice balance; statement version; aging snapshot; collections status; payment-application effect; refund or unapplied state; interface identifiers; close handoff; preparer; reviewer; exception owner; and resolution event',
    states: 'approved not posted, posted at source, invoice updated, account updated, statement updated, aging updated, collections hold updated, payment state updated, downstream pending, interface rejected, version mismatch, amount mismatch, tax mismatch, reversal linked, refund decision required, inaccessible, and unresolved',
    tests: 'freeze the approved version; reconcile components to the total; trace forward into every declared dependency and backward from sampled downstream changes; compare effective and processing timestamps; inspect partial, multi-invoice, reversal, and closed-period cases; prevent a later version from overwriting prior evidence; reconcile opening plus credits and reversals to closing; and independently review every mismatch',
    interpretation: 'A balanced source ledger does not prove that statements, aging, collections, or customer records reflect the same version. A downstream difference may be expected timing, an interface defect, or an owner-approved treatment. Report propagation state and timing separately from the decision about correction.',
    limitations: 'System architecture, posting schedules, tax engines, foreign currency, closed periods, statement timing, payment application, refund controls, integrations, and incomplete historical snapshots may prevent exact alignment. This study cannot approve credits, refunds, write-offs, tax treatment, accounting entries, collections actions, or customer explanations.',
    service: '/services/credit-memo-administration', serviceLabel: 'Review credit-memo administration support', sources: [greenBook, nist, fasb, cisa],
  },
  {
    slug: 'research-outsourced-billing-collections-contact-restriction-lineage-2026', topic: 'collections contact restriction lineage',
    title: 'Collections Contact Restriction Research: Did the Queue Use the Current Communication Rule?',
    excerpt: 'A version-aware study of approved destinations, channel restrictions, dispute holds, contact attempts, responses, and escalation evidence.',
    question: 'Before each collections contact attempt, can a reviewer reconstruct the account facts, approved destination, channel permission, active restriction or dispute hold, template version, and owner instruction that governed the action?',
    decision: 'whether collections follow-up can be delegated as bounded factual outreach and recordkeeping without transferring authority over contact policy, disputes, settlements, concessions, or legal escalation',
    unit: 'one attempted, suppressed, or scheduled contact linked to one account-state snapshot and one approved communication instruction',
    population: 'all contact candidates and attempts during the selected period, including email, telephone, portal, postal, automated, manual, suppressed, returned, wrong-destination, disputed, represented-party, hardship, settlement-request, complaint, privacy concern, inaccessible, and unresolved records',
    evidence: 'account and invoice locators; balance-source version; aging date; payment and credit activity; dispute or hold state; destination source and verification time; approved channel; contact restriction and effective period; timezone and schedule rule; template and script version; preparer; sender or system; attempt identifier and time; exact factual response; promise or request as reported; escalation; owner decision; and next action',
    states: 'eligible under instruction, restriction active, dispute hold active, destination unverified, channel unavailable, timing blocked, template current, template stale, sent, delivered state observed, returned, response received, owner review required, escalated, suppressed with evidence, inaccessible, and unresolved',
    tests: 'reconstruct state immediately before each attempt; compare destinations with approved sources; test restrictions and holds by effective time; inspect timezone and cadence boundaries; preserve template versions; separate sent from delivered and answered; link responses without converting customer statements into promises or concessions; sample suppressed records; reconcile candidates to attempts and holds; and independently review every potential restriction conflict',
    interpretation: 'A technically delivered message does not prove that contact was permitted, received by the intended person, or substantively resolved. A reported promise or dispute is an observed communication that needs owner handling, not authority for the specialist to change terms, balances, or strategy.',
    limitations: 'Applicable law, customer agreements, local policy, contact consent, representation notices, privacy requirements, shared destinations, channel-provider semantics, timezone, incomplete history, and account-system latency constrain the analysis. The method cannot provide legal conclusions, approve contact strategy, settle a balance, change a payment plan, waive an amount, or decide a dispute.',
    service: '/services/collections-follow-up', serviceLabel: 'Review collections-follow-up support', sources: [greenBook, ftc, nist, cisa],
  },
];

const specificAnalysis: Record<string, string[]> = {
  'research-outsourced-billing-invoice-delivery-acknowledgment-integrity-2026': [
    'Delivery-layer analysis. The study should model release, dispatch, provider acceptance, destination handling, and human access as separate events because each answers a different question. For email, a provider may accept a message before a recipient server rejects, quarantines, or routes it. For a portal, publication may occur before the customer account can authenticate or locate the document. For electronic interchange, a transport acknowledgment may confirm syntax while a later business response rejects the invoice. The evidence table should therefore retain the native event name and code, a plain-language classification, and the documented reason for that classification. A team should never collapse accepted, delivered, viewed, and acknowledged into a single successful flag. Doing so hides the exact layer that needs repair and can trigger collections activity from an invoice the destination could not use.',
    'Exception experiment. Divide failed or uncertain deliveries by channel, destination-source age, invoice correction status, error class, and retry path. Select every permanent rejection and a bounded sample of apparent successes. Starting with the released invoice version, ask a second reviewer to recover the destination source, dispatch identifier, raw response, retry history, and final state. Then start with sampled provider events and trace backward to ensure that unrelated messages were not joined by customer name or timestamp alone. Report how many exceptions were resolved by correcting destination data, regenerating a transmission, publishing a corrected version, or obtaining an owner decision. Keep technical repair time separate from time waiting for customer, policy, or legal interpretation. This design helps a buyer decide whether the problem is source maintenance, transport monitoring, invoice version control, or unclear escalation authority.',
  ],
  'research-outsourced-billing-subscription-retry-authorization-state-2026': [
    'State-machine analysis. Build a time-ordered state for each subscription before evaluating attempts. A useful sequence includes active plan version, billed amount, payment-method token status, pause or cancellation event, dispute or contact restriction, retry-policy version, scheduled attempt, actual submission, processor response, and next scheduled action. Events arriving later should not be backfilled as though they were known earlier. Instead, record the effective time supplied by the source and the time the billing system learned it. This distinction exposes race conditions: a cancellation may be effective before an attempt but reach the payment service afterward, or a processor timeout may leave submission status uncertain while an automatic scheduler prepares another try. Neither circumstance should be forced into a simple valid-or-invalid label without preserving the timing conflict.',
    'Attempt-cohort experiment. Group attempts by ordinal position, hours since the prior result, policy version, initiating actor, response family, and account-state conflict. Reconcile subscriptions, billing events, and processor attempts in both directions so missing attempts and unlinked attempts remain visible. For uncertain confirmations, hold duplicate retry analysis apart from decline analysis; a transport timeout is not a decline. Sample manual attempts and compare their approval evidence with the exact amount, currency, account, and time submitted. Measure attempts stopped by a pause, cancellation, restriction, owner hold, or confirmed success as well as attempts executed. The resulting distribution can reveal scheduler lag, incomplete state propagation, ambiguous response mapping, or excessive manual intervention. It cannot establish the best retry cadence, because commercial terms, payment-network rules, customer treatment, and applicable requirements remain outside this documentary test.',
  ],
  'research-outsourced-billing-usage-late-arrival-cutoff-cohort-2026': [
    'Latency decomposition. For every late event, calculate separate intervals from event occurrence to source creation, source creation to extraction, extraction to receipt, and receipt to ingestion. Negative or impossible intervals should become clock or timezone exceptions rather than being silently corrected. Segment results by source device, feed, customer mapping, event type, correction status, and boundary hour. A concentration in source-to-extraction time suggests a different remedy from a concentration in receipt-to-ingestion time. Corrections also require their own lineage: the original may have arrived on time while the reversal arrived late, so treating both as ordinary late volume obscures the causal sequence. Preserve quantities in source units before any conversion and reconcile the late cohort to the frozen on-time cohort without changing the original cutoff population.',
    'Cycle-disposition experiment. Create an opening register of unresolved late events from the prior cycle, add newly detected events, and subtract only dispositions supported by an owner decision or documented rule. For each event, show the candidate source period and candidate billing cycle separately. Trace a sample forward into invoice lines, approved carryforward, supported exclusion, or continued hold, then trace sampled invoice additions backward to the late register. Compare what would change under alternative cutoff windows as sensitivity analysis, clearly labeled hypothetical rather than policy. Report event counts and quantities, because one very large aggregate can distort a count-only view. Also report how many decisions depended on missing contract or mapping evidence. This tells a buyer whether to improve feed timing, cutoff instructions, mapping ownership, or exception review without pretending the research decides when revenue or a customer charge belongs.',
  ],
  'research-outsourced-billing-credit-memo-downstream-propagation-2026': [
    'Dependency-graph analysis. Declare every downstream consumer before testing: invoice subledger, customer balance, statement generator, aging report, collections queue, cash-application workspace, refund queue, tax record where applicable, general-ledger handoff, and close package. For each consumer, document whether updates are synchronous, scheduled, manually triggered, or intentionally absent. The expected value may differ by system, so compare the approved credit components with a written transformation rule rather than demanding identical totals everywhere. A statement generated before posting can validly show the earlier balance, while a collections queue refreshed afterward should not continue from a superseded amount without an explained delay. Version identifiers, effective times, processing times, and batch identifiers make those cases distinguishable.',
    'Propagation experiment. Select all interface rejects and a risk-based sample of ordinary credits, ensuring coverage of partial, multi-invoice, reversed, tax-bearing, unapplied, and closed-period examples. Trace each approved version across the declared graph and record first correct visibility at every node. Then sample downstream balance changes and trace backward to prevent unrelated adjustments from being credited to the memo. Reconcile credit amounts, reversals, and unapplied components at each boundary while preserving currency and sign conventions. Measure propagation lag by dependency rather than as one end-to-end average, and report missing snapshots as unknown. A recurring delay at one interface suggests a scheduling or integration question; inconsistent versions across several consumers may indicate change-control weakness. Neither pattern authorizes a repost, refund, tax change, journal, or collections adjustment without the named owner.',
  ],
  'research-outsourced-billing-collections-contact-restriction-lineage-2026': [
    'Pre-contact state analysis. Construct the evidence snapshot that was available immediately before an outreach event. The snapshot should combine the balance-source version, recent payments and credits, dispute or hardship state, destination source, channel restriction, cadence rule, local-time window, template version, and any named owner instruction. Do not use a later-corrected destination or restriction to make an earlier action appear compliant. Conversely, a later complaint does not prove the earlier queue contained that information. Recording both effective time and observed time lets reviewers identify whether the issue was a missing source, delayed synchronization, ignored instruction, or genuinely new information. Because legal and contractual rules vary, the study should test adherence to the buyer-approved rule set and route interpretation questions rather than pronounce a contact lawful.',
    'Suppression-and-attempt experiment. Begin with the full candidate queue, not only messages that were sent. Reconcile every candidate to an attempted, suppressed, held, duplicated, or unresolved state. Stratify suppressed work by active dispute, unverified destination, channel restriction, cadence limit, owner hold, and technical failure; excessive suppression can be as operationally important as excessive contact. For attempted outreach, compare the exact template and destination version with the pre-contact snapshot, then preserve provider responses and customer statements without paraphrasing them into commitments. Independently review wrong-destination, stale-template, and restriction-conflict candidates. Measure time from new restriction evidence to queue suppression and from a factual response to owner escalation. These measures can identify synchronization and routing gaps while keeping settlements, concessions, payment plans, dispute outcomes, and changes in contact strategy outside the specialist role.',
  ],
};

const buildSep28Body = (x: ResearchSeed) => {
  const base = buildDecisionResearchBody(x, checked);
  const appendixLength = x.sources.length + 1;
  return [...base.slice(0, -appendixLength), ...specificAnalysis[x.slug], ...base.slice(-appendixLength)];
};

export const sep28ResearchBatch = seeds.map((x) => ({
  slug: x.slug, title: x.title, excerpt: x.excerpt, published, datePublished: published, updated: published,
  featuredImage, body: buildSep28Body(x),
  serviceCta: { href: x.service, label: x.serviceLabel, title: 'Turn this research design into a controlled billing routine', body: 'Define the population, evidence, stopping points, review owner, and approval boundary before assigning volume.' },
}));

export const sep28ResearchTopics = seeds.map(({ slug, topic, sources }) => ({ slug, topic, sources }));
