const published = '2026-09-07' as const;
const blogImage = '/aug20-heroes/billing-operations-close-package-checklist.png';
const researchImage = '/aug20-research-heroes/research-medical-billing-claim-evidence-lineage.png';
const titleFromSlug = (slug:string) => slug
  .replace(/^sep7-medical-billing-|^research-medical-billing-sep7-/, '')
  .replace(/-2026$/, '')
  .split('-')
  .map((word) => ({era:'ERA',cob:'COB'}[word] ?? `${word.charAt(0).toUpperCase()}${word.slice(1)}`))
  .join(' ');

type BlogTopic = {
  slug: string;
  title: string;
  focus: string;
  evidence: string;
  snag: string;
  owner: string;
};

const blogTopics: BlogTopic[] = [
  {slug:'sep7-medical-billing-era-file-to-posting-batch-crosswalk',title:'September 7 — ',focus:'an electronic remittance file that has entered the posting queue',evidence:'the file identifier, trace number, receipt time, posting batch, claim lines, and any rejected import rows',snag:'one ERA can feed more than one batch, while a reimport can make the same payment appear twice',owner:'cash posting owner'},
  {slug:'sep7-medical-billing-authorization-unit-depletion-ledger',title:'September 7 — ',focus:'authorized units used across a series of encounters',evidence:'the authorization record, encounter dates, billed units, claim versions, and payer responses',snag:'scheduled, documented, billed, and adjudicated units may describe different stages of the same service',owner:'authorization and coding owner'},
  {slug:'sep7-medical-billing-denial-letter-to-claim-version-link',title:'September 7 — ',focus:'a denial notice that must be matched to the right claim version',evidence:'the original notice, payer control number, service lines, submission receipts, and correction history',snag:'a notice can arrive after a replacement claim has changed the queue view',owner:'denial management owner'},
  {slug:'sep7-medical-billing-refund-check-clearance-followup-log',title:'September 7 — ',focus:'an approved refund after the check or electronic payment leaves the organization',evidence:'the approval, payment reference, issue date, delivery evidence, bank status, and account entry',snag:'an issued check is not the same thing as a cleared check, and neither fact alone proves the account was updated correctly',owner:'authorized refund and accounting owner'},
  {slug:'sep7-medical-billing-cob-response-source-comparison',title:'September 7 — ',focus:'conflicting payer-order information across permitted sources',evidence:'eligibility responses, payer notices, claim responses, patient-provided records, and effective dates',snag:'the newest response may not describe the service date under review',owner:'coordination of benefits owner'},
  {slug:'sep7-medical-billing-charge-entry-source-document-index',title:'September 7 — ',focus:'the source documents available before charge entry review',evidence:'the encounter locator, approved charge source, service date, provider reference, document version, and access state',snag:'document presence can be mistaken for coding completeness or approval to enter a charge',owner:'qualified coding or charge entry owner'},
  {slug:'sep7-medical-billing-payer-portal-message-capture-register',title:'September 7 — ',focus:'payer portal messages that may change or disappear from the current view',evidence:'the original wording, message identifier, claim locator, retrieved time, attachment reference, and permitted screenshot location',snag:'a copied summary can lose qualifiers, dates, or the claim version named in the source',owner:'billing owner responsible for payer follow-up'},
  {slug:'sep7-medical-billing-rejected-era-line-recovery-queue',title:'September 7 — ',focus:'remittance lines that did not enter the normal posting workflow',evidence:'the ERA segment, import error, claim match candidates, amount, batch result, and later posting reference',snag:'a rejected line can vanish from operational totals even though the related deposit remains',owner:'cash posting and systems owner'},
  {slug:'sep7-medical-billing-appeal-submission-receipt-chain',title:'September 7 — ',focus:'evidence that an approved appeal packet reached the intended channel',evidence:'the approved packet version, destination, transmission event, receipt wording, timestamps, and returned messages',snag:'a sent status or fax log does not always establish acceptance by the intended payer workflow',owner:'appeals owner'},
  {slug:'sep7-medical-billing-provider-enrollment-document-expiry-board',title:'September 7 — ',focus:'enrollment documents nearing a stated expiration or renewal point',evidence:'the governing record, document version, effective period, submitted renewal, receipt, and current response',snag:'an internal reminder date can be mistaken for a payer deadline or proof of continued participation',owner:'provider enrollment owner'},
  {slug:'sep7-medical-billing-patient-payment-plan-exception-register',title:'September 7 — ',focus:'account activity that does not match the recorded payment plan schedule',evidence:'the authorized plan, installment dates, receipts, reversals, account postings, and approved communications',snag:'a missed or partial installment does not authorize staff to change terms, move money, or contact the patient outside policy',owner:'patient financial services owner'},
  {slug:'sep7-medical-billing-end-of-day-claim-transmission-receipt',title:'September 7 — ',focus:'claims prepared near the daily transmission cutoff',evidence:'the frozen outbound count, claim identifiers, submission batch, clearinghouse acknowledgment, rejects, and carryforward list',snag:'prepared, transmitted, received, and accepted are separate events that dashboards sometimes collapse',owner:'claim submission owner'},
];

export type Sep7BlogArticle = {slug:string;title:string;description:string;published:typeof published;featuredImage:string;body:string[]};

export const sep7BlogBatch: Sep7BlogArticle[] = blogTopics.map((topic, index) => ({
  slug: topic.slug,
  title: titleFromSlug(topic.slug),
  description: `A September 7 field guide for controlling ${topic.focus} in outsourced medical billing support.`,
  published,
  featuredImage: blogImage,
  body: [
    `${topic.title} deals with ${topic.focus}. Open one record for the item before anyone starts comparing screens. Give it a stable locator, a queue reason, the first observed state, and a named ${topic.owner}. This small bit of discipline matters when work passes between shifts in the Philippines and a client team elsewhere. The record should tell the next person what was known at handoff, not merely what the system shows now.`,
    `Collect ${topic.evidence}. Keep event time separate from retrieval, entry, review, and decision time. Save the source name and version in the approved system. If a field is blank, record it as blank. If access fails, name the inaccessible source and the access owner. Do not fill either gap with a likely value from a similar claim.`,
    `The recurring trap is that ${topic.snag}. Build a side-by-side comparison instead of writing a blended narrative. Show the source value, local value, timestamp, stable identifier, and whether the entry is observed, calculated, owner-interpreted, or still unknown. A later record may narrow the question, but it should not erase the earlier evidence state.`,
    `Define the unit before counting. For this control, decide whether one row means a claim, claim version, service line, remittance line, payment, notice, document, or transmission. Freeze the opening population with the cutoff and timezone. Put late arrivals and reopened items in their own columns. Otherwise, a clean closing count can hide work that entered after the denominator moved.`,
    `Support staff can retrieve permitted records, compare fields, reproduce arithmetic, index evidence, and draft a factual question. The ${topic.owner} interprets policy and authorizes any action that changes a claim, code, account, balance, submission, access right, refund, or external communication. The queue should make that stopping point obvious. It should never rely on a worker remembering an unwritten exception.`,
    `Use plain states that describe what happened: source confirmed, comparison ready, conflict, missing evidence, access blocked, awaiting owner, authorized action, or carried forward. Each change needs an actor, time, and supporting reference. "Sent" is not a receipt. "Resolved" is not useful without the approved result or a link to the decision that closed the item.`,
    `Review an ordinary item and at least one awkward case when those cases exist. A second reviewer should be able to repeat the check from the recorded sources. If the answer changes, note whether the disagreement came from scope, source selection, date handling, identifier matching, or authority. Keep the disagreement in the record. It often points to the part of the routine that needs clearer instructions.`,
    `Close the day by reconciling every opening item to its current state. Explain duplicates and exclusions. Give each unresolved item one next actor, one bounded question, and a dated review trigger. The September 7, 2026 close package proves how the team handled the defined evidence. It does not prove payment, coverage, coding accuracy, compliance, or the final account outcome.`,
    `Privacy rules do not loosen because a deadline is close. Store protected details in approved billing tools, use the minimum locator needed in shared worklists, and never borrow a colleague's credentials. When a worker lacks access, the correct output is an access exception routed to its owner. Copying sensitive material into chat only creates a second problem.`,
    `The practical test for control ${index + 1} is simple: another authorized person should be able to find the same source, see the same uncertainty, and understand who must decide next. If the record can do that, the outsourced team has produced a useful handoff without claiming authority it does not have.`,
  ],
}));

export const sep7BlogSlugs = sep7BlogBatch.map((article) => article.slug);

type ResearchSeed = {slug:string;title:string;question:string;unit:string;method:string;limitations:string;sources:string[]};
const researchSeeds: ResearchSeed[] = [
  {slug:'research-medical-billing-sep7-era-import-rejection-recovery-2026',title:'September 7 — ',question:'Which evidence gaps explain why remittance lines rejected during import remain outside the normal posting queue?',unit:'one remittance line rejected by an identified import event',method:'Stratify by file format error, missing claim match, duplicate signal, invalid local mapping, access block, and unresolved cause.',limitations:'Interfaces can transform fields, error labels can change, and later manual posting may not preserve the original rejection.',sources:['https://www.cms.gov/medicare/coding-billing/electronic-billing/electronic-remittance-advice','https://www.caqh.org/core/operating-rules','https://www.hhs.gov/hipaa/for-professionals/security/index.html']},
  {slug:'research-medical-billing-sep7-authorization-unit-variance-2026',title:'September 7 — ',question:'How often do source authorization units, documented encounter units, claim units, and payer responses disagree in a frozen review cohort?',unit:'one authorization and service-date pairing',method:'Compare each permitted source at the same unit and time boundary, while keeping scheduled, documented, billed, and adjudicated values separate.',limitations:'Payer rules and clinical documentation vary, source access can be restricted, and a numerical match does not establish medical necessity.',sources:['https://www.cms.gov/medicare/coverage','https://www.hhs.gov/hipaa/for-professionals/privacy/index.html','https://www.ahrq.gov/health-literacy/improve/precautions/index.html']},
  {slug:'research-medical-billing-sep7-appeal-receipt-reproducibility-2026',title:'September 7 — ',question:'Can a second reviewer reproduce proof that an approved appeal packet reached the intended payer channel?',unit:'one approved appeal packet version and its transmission attempt',method:'Retain the destination, submission event, receipt wording, returned message, source timestamps, and reviewer classification.',limitations:'Channel receipts may prove transmission rather than substantive acceptance, and payer-specific appeal rules limit comparisons.',sources:['https://www.cms.gov/medicare/appeals-grievances','https://www.cms.gov/regulations-and-guidance/guidance/manuals/internet-only-manuals-ioms-items/cms018912','https://www.hhs.gov/hipaa/for-professionals/privacy/index.html']},
  {slug:'research-medical-billing-sep7-cob-source-conflict-aging-2026',title:'September 7 — ',question:'How long do conflicts among dated payer-order sources remain unresolved, and which missing decision or record explains the wait?',unit:'one service-date-specific payer-order conflict',method:'Measure named intervals between source retrieval, conflict detection, owner receipt, requested evidence, and documented disposition.',limitations:'Current eligibility does not necessarily describe an earlier service date, patient reports may be incomplete, and coverage interpretation belongs to qualified owners.',sources:['https://www.cms.gov/medicare/coordination-benefits-recovery/overview/coordination-benefits','https://www.caqh.org/core/operating-rules','https://www.hhs.gov/hipaa/for-professionals/privacy/index.html']},
  {slug:'research-medical-billing-sep7-claim-transmission-acknowledgment-gap-2026',title:'September 7 — ',question:'Where does evidence stop between claim preparation, outbound transmission, clearinghouse receipt, payer receipt, and acceptance?',unit:'one claim version in one identified outbound batch',method:'Build an event chronology from stable claim and batch identifiers, then classify the first unsupported transition.',limitations:'Acknowledgment formats differ, identifiers can be transformed, missing history can bias the cohort, and acceptance does not prove payment or coding correctness.',sources:['https://www.cms.gov/medicare/coding-billing/electronic-billing','https://x12.org/products/health-care-claim-837','https://www.caqh.org/core/operating-rules']},
];

export type Sep7ResearchArticle={slug:string;title:string;excerpt:string;published:typeof published;datePublished:typeof published;updated:typeof published;featuredImage:string;body:string[]};
export const sep7ResearchBatch: Sep7ResearchArticle[] = researchSeeds.map((study, index) => ({
  slug: study.slug,
  title: `${titleFromSlug(study.slug)} Research`,
  excerpt: `A September 7 source-based study asking: ${study.question}`,
  published,datePublished:published,updated:published,featuredImage:researchImage,
  body:[
    `Research question: ${study.question}`,
    `Scope and unit: This September 7, 2026 study examines administrative evidence available to an outsourced medical billing support team. The unit is ${study.unit}. It does not test clinical care, legal compliance, contract entitlement, staff performance, or the correctness of a final payer decision. That boundary keeps a workflow study from drifting into conclusions its records cannot support.`,
    `Cohort design: Freeze the population before reviewing outcomes. Record the source report, filters, cutoff, timezone, duplicate rule, and exclusions. Include ordinary records, missing evidence, conflicts, access blocks, reopened items, and unresolved work. Study ${index + 1} reports raw counts with every rate so a change in the denominator remains visible.`,
    `Collection method: Preserve the original source wording, stable identifiers, versions, event times, retrieval times, assigned role, and approved evidence location. ${study.method} A copied queue label is an observation about the local system, not a substitute for the source record. Calculated intervals should show their start and end events.`,
    `Reliability check: Give a mixed sample to a second authorized reviewer. That reviewer should reconstruct the population membership, select the same source fields, and classify the evidence without seeing the first result. Record disagreements by cause. Differences in source choice, date treatment, or identifier linkage are findings, not editing errors to hide.`,
    `Analysis: Publish categories for source confirmed, source conflict, missing record, access blocked, owner interpretation, superseded evidence, and unresolved at cutoff. Keep sequence and causation separate. An event that occurs after another may help reconstruct the workflow, but timing alone does not show why the first event occurred or who was responsible.`,
    `Operational boundary: Support staff may retrieve approved records, compare fields, calculate transparent intervals, and prepare a neutral question. They may not select codes, decide medical necessity or coverage, interpret an unassigned contract, change an account, move money, grant access, submit an unapproved record, or promise an outcome. A named owner retains those decisions.`,
    `Limitations: ${study.limitations} The cohort may also be non-random and local procedures may differ from another organization. Report missing values and inaccessible history. Do not treat later success as proof that an earlier step was properly documented.`,
    `Conclusion: ${study.title} can show where a defined evidence chain breaks and which owner must respond. Its result is a reproducible description of the observed cohort, not a forecast. Unknowns remain in the denominator and any owner interpretation remains labeled as such.`,
    ...study.sources.map((source) => `Source checked September 7, 2026: ${source}`),
  ],
}));
