const published = '2026-09-09' as const;
const blogImage = '/aug20-heroes/billing-operations-close-package-checklist.png';
const researchImage = '/aug20-research-heroes/research-medical-billing-claim-evidence-lineage.png';

type BlogSeed = { slug:string; title:string; situation:string; evidence:string; trap:string; owner:string; close:string };
const blogSeeds: BlogSeed[] = [
  {slug:'medical-billing-downtime-claim-intake-recovery',title:'After the Billing System Comes Back: Rebuild the Claim Intake Trail',situation:'claim information collected during a billing-system outage',evidence:'the downtime log, encounter locator, source document, entry timestamp, interface receipt, and recovery batch',trap:'the recovered total may look right while one encounter was entered twice or never crossed the interface',owner:'claim intake and application owner',close:'every downtime item has one source-to-system disposition'},
  {slug:'medical-billing-partial-era-import-exception',title:'A Partial ERA Import Is Not a Balanced Posting Batch',situation:'an ERA that imported only some of its reported transactions',evidence:'the original 835, import control report, remittance totals, accepted lines, rejected lines, and deposit trace',trap:'a successful file status can coexist with missing service lines or an incomplete account posting',owner:'remittance and cash-posting owner',close:'file, batch, line, and deposit counts reconcile without netting away exceptions'},
  {slug:'medical-billing-secondary-claim-pending-primary-record',title:'Secondary Claims Should Wait for the Right Primary Record',situation:'a secondary claim queued before its primary adjudication evidence is complete',evidence:'the primary claim version, remittance, patient-responsibility fields, crossover indicator, secondary payer record, and queue history',trap:'a visible primary balance does not prove that the secondary transaction has the evidence or sequencing it needs',owner:'coordination-of-benefits owner',close:'the held claim points to the exact missing or conflicting primary evidence'},
  {slug:'medical-billing-corrected-claim-frequency-code-check',title:'Before a Corrected Claim Leaves, Check the Version and Frequency Code',situation:'a corrected or replacement claim prepared for transmission',evidence:'the original claim, payer control number, proposed version, frequency field, change reason, approval, and transmission plan',trap:'a correct field change can still be attached to the wrong predecessor or sent through the wrong transaction path',owner:'qualified claim correction owner',close:'the approved change, predecessor, transaction type, and receipt remain linked'},
  {slug:'medical-billing-appeal-deadline-source-card',title:'Build the Appeal Deadline Card From the Notice, Not Memory',situation:'an appeal or reconsideration deadline entering a work queue',evidence:'the dated notice, receipt evidence, payer instructions, claim reference, governing workflow, calculation, and reviewer note',trap:'staff may treat a familiar interval as universal even when the notice, channel, or review stage differs',owner:'appeal and compliance owner',close:'the recorded date is reproducible from a cited source and approved interpretation'},
  {slug:'medical-billing-unapplied-cash-candidate-match',title:'Unapplied Cash Needs Candidate Matches, Not a Forced Answer',situation:'a payment or deposit that lacks a defensible account match',evidence:'the bank trace, payer or sender detail, amount, receipt date, remittance search, account candidates, and prior investigation',trap:'matching on amount and a similar name can move money to the wrong account and hide the original uncertainty',owner:'cash application and accounting owner',close:'each candidate is supported or rejected by named evidence, with the item still visible if unresolved'},
  {slug:'medical-billing-payer-portal-download-provenance',title:'Give Every Payer Portal Download a Provenance Label',situation:'a report, letter, or response downloaded from a payer portal',evidence:'the portal area, retrieval time, query filters, account or claim locator, file name, visible effective date, and permitted storage path',trap:'a downloaded file can lose the screen context that explains its population, freshness, and relationship to a claim',owner:'payer follow-up and records owner',close:'another authorized reviewer can repeat the retrieval or understand why it cannot be repeated'},
  {slug:'medical-billing-credit-balance-refund-request-intake',title:'A Refund Request Is an Intake Event, Not a Refund Decision',situation:'a payer or patient refund request arriving for review',evidence:'the request, delivery channel, claimed amount, account ledger, remittances, prior transfers, correspondence, and due-date source',trap:'the requested amount may omit reversals, offsets, duplicate postings, or the policy context required for a decision',owner:'refund, accounting, and compliance owner',close:'receipt, evidence review, decision authority, and any approved release stay separate'},
  {slug:'medical-billing-missing-charge-source-followup',title:'When a Charge Looks Missing, Trace the Source Before Adding Work',situation:'an encounter or service that appears absent from the billing queue',evidence:'the encounter record, status history, source interface, charge entry report, hold reason, cancellation evidence, and owner assignment',trap:'absence from one report can mean a filter, timing difference, valid hold, or interface break rather than a missing charge',owner:'charge capture and coding owner',close:'the exception names the layer where the record stopped and the authorized next check'},
  {slug:'medical-billing-patient-payment-reversal-handoff',title:'Patient Payment Reversals Need a Two-Ledger Handoff',situation:'a patient payment reversed by processor, bank, or approved account action',evidence:'the original receipt, processor event, bank result, account posting, reversal reason, communications record, and approval',trap:'the processor and patient ledger may update on different dates, leaving a temporary or persistent mismatch',owner:'patient financial services and accounting owner',close:'processor money movement and account treatment are independently reconciled'},
  {slug:'medical-billing-batch-control-total-change-log',title:'If a Billing Batch Total Changes, Keep the Before-and-After Math',situation:'a claim, invoice, or payment batch whose control total changed during preparation',evidence:'the frozen opening extract, additions, removals, corrections, component amounts, reason codes, approvals, and final release total',trap:'overwriting the opening number removes the evidence needed to explain why a balanced batch changed',owner:'batch preparation and release owner',close:'every movement between opening and release totals has a source row and disposition'},
  {slug:'medical-billing-shared-queue-stale-owner-review',title:'Stale Queue Owners Create Quiet Billing Gaps',situation:'work still assigned to an inactive, transferred, or unavailable queue owner',evidence:'the queue export, assignment history, user status, last action, aging clock, coverage rule, and reassignment approval',trap:'the item remains technically assigned while no accountable person is watching its next event or deadline',owner:'billing operations and access-governance owner',close:'each stale assignment has an approved current owner without erasing its prior history'},
];

export type Sep9BlogArticle={slug:string;title:string;description:string;published:typeof published;featuredImage:string;body:string[]};
export const sep9BlogBatch:Sep9BlogArticle[]=blogSeeds.map((x,index)=>({
  slug:x.slug,title:x.title,published,featuredImage:blogImage,
  description:`A September 9 operating routine for ${x.situation}, grounded in traceable source evidence and clear decision ownership.`,
  body:[
    `Start with the actual event: ${x.situation}. Assign a stable locator, record when the item entered the workflow, and name the ${x.owner}. The record should make sense to an authorized colleague who did not watch the event happen.`,
    `Gather the evidence before proposing an action: ${x.evidence}. Preserve original wording, identifiers, and timestamps in approved systems. Retrieval time, event time, system-entry time, and review time answer different questions and should not be collapsed.`,
    `The easy mistake is assuming that ${x.trap}. Mark each field as observed, externally reported, calculated, owner-interpreted, or unknown. If sources disagree, retain both values and route the conflict instead of silently choosing the tidier one.`,
    `For routine ${index+1}, define the unit before counting: claim version, service line, remittance line, deposit, account event, document, or queue item. Freeze the opening population and list late arrivals separately. Otherwise the denominator moves while the team is trying to explain it.`,
    `Support staff may retrieve permitted records, compare fields, reproduce documented arithmetic, index files, and draft a bounded factual question. The ${x.owner} retains decisions that change coding, clinical meaning, claim content, money, access, submission, legal interpretation, or external communication.`,
    `Use statuses that reveal the work: evidence gathered, conflict found, access blocked, awaiting owner, authorized action, or carried forward. A generic completed label is not enough unless the record says what changed, who approved it, and where the result can be verified.`,
    `Before close, have a second authorized reviewer repeat one ordinary item and one exception when available. Compare source selection, identifiers, timing, scope, and arithmetic. A disagreement often exposes an unstated assumption in the routine.`,
    `The close test is precise: ${x.close}. Reconcile every opening item to a current state, give unresolved work one next actor and review date, and keep missing or inaccessible evidence visible in the count.`,
    `Keep protected information in approved tools and use only the minimum necessary locator in shared trackers. An access problem belongs with the access owner; it is never permission to borrow credentials or move sensitive records into an unapproved channel.`,
    `This September 9, 2026 guide is an administrative control, not a clinical, coding, coverage, contract, legal, or accounting determination. Its value is practical: it preserves what happened and delivers a well-bounded question to the person authorized to decide.`
  ]
}));
export const sep9BlogSlugs=sep9BlogBatch.map(x=>x.slug);

type ResearchSeed={slug:string;title:string;question:string;unit:string;method:string;limits:string;sources:string[]};
const researchSeeds:ResearchSeed[]=[
 {slug:'research-medical-billing-partial-era-import-completeness-2026',title:'Partial ERA Import Completeness: Can File Success Hide Missing Lines?',question:'Can source and import evidence identify ERA transactions that never reached the posting batch?',unit:'one source 835 transaction and its local import disposition',method:'Reconcile file control values, transaction and service-line counts, import messages, batch rows, deposits, and unresolved exceptions without relying on a successful file-level status.',limits:'Vendor transformations, inaccessible raw files, split deposits, and delayed corrections can prevent complete reconstruction.',sources:['https://www.cms.gov/medicare/coding-billing/electronic-billing/electronic-remittance-advice','https://x12.org/products/health-care-claim-paymentadvice-835','https://www.caqh.org/core/operating-rules']},
 {slug:'research-medical-billing-downtime-recovery-reconciliation-2026',title:'Billing Downtime Recovery Research: Which Intake Records Survive the Handoff?',question:'How completely can billing items recorded during downtime be traced into the restored production workflow?',unit:'one downtime intake item with a stable approved locator',method:'Freeze the outage window and compare downtime logs, source documents, interface events, production entries, duplicate checks, exception states, and owner sign-off.',limits:'Informal notes may be unavailable, clocks can disagree, and a production entry does not prove every source field was transferred correctly.',sources:['https://www.hhs.gov/hipaa/for-professionals/security/guidance/cybersecurity/index.html','https://www.nist.gov/cyberframework','https://www.cisa.gov/resources-tools/resources/healthcare-and-public-health-sector']},
 {slug:'research-medical-billing-appeal-deadline-reproducibility-2026',title:'Appeal Deadline Reproducibility: Can Two Reviewers Reach the Same Date?',question:'When given the same notice and approved guidance, do authorized reviewers calculate the same appeal deadline and identify the same uncertainty?',unit:'one notice, claim reference, review stage, and proposed deadline calculation',method:'Preserve the notice wording, notice and receipt dates, channel, review stage, cited guidance, calculation convention, timezone, reviewer result, and owner resolution.',limits:'Payer and jurisdiction rules vary; notice language may be ambiguous; this study cannot determine legal timeliness or appeal merit.',sources:['https://www.cms.gov/medicare/appeals-grievances/fee-for-service','https://www.cms.gov/medicare/appeals-grievances/managed-care','https://www.hhs.gov/hipaa/for-professionals/privacy/index.html']},
 {slug:'research-medical-billing-unapplied-cash-match-evidence-2026',title:'Unapplied Cash Match Evidence: How Strong Is the Proposed Link?',question:'Which evidence combinations support a reproducible candidate match for unapplied cash without forcing account placement?',unit:'one unapplied receipt and one proposed account or remittance relationship',method:'Compare trace identifiers, sender or payer evidence, amounts, dates, remittance searches, account candidates, prior postings, exclusions, and independent reviewer classifications.',limits:'Similar amounts and names are weak identifiers, bank data may be truncated, and local accounting policy controls final application.',sources:['https://www.cms.gov/medicare/claims/medicare-remittance-advice','https://www.caqh.org/core/operating-rules','https://www.nist.gov/privacy-framework']},
 {slug:'research-medical-billing-stale-queue-ownership-cohort-2026',title:'Stale Queue Ownership Cohort: When Assigned Work Has No Active Owner',question:'How often does billing work remain assigned after the responsible user or coverage arrangement becomes inactive?',unit:'one queue item and its assignment state at the frozen cutoff',method:'Join approved queue exports, assignment history, user status, last activity, aging fields, coverage rules, reassignments, and access-review evidence while preserving prior ownership.',limits:'Status feeds may lag, shared queues complicate accountability, and inactivity does not by itself prove neglect or financial impact.',sources:['https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final','https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/index.html','https://www.cisa.gov/resources-tools/resources/cybersecurity-performance-goals']},
];
export type Sep9ResearchArticle={slug:string;title:string;excerpt:string;published:typeof published;datePublished:typeof published;updated:typeof published;featuredImage:string;body:string[]};
export const sep9ResearchBatch:Sep9ResearchArticle[]=researchSeeds.map((x,index)=>({slug:x.slug,title:x.title,excerpt:`A September 9 evidence study asking: ${x.question}`,published,datePublished:published,updated:published,featuredImage:researchImage,body:[
 `Research question: ${x.question}`,
 `Scope: This September 9, 2026 study concerns administrative evidence available to an outsourced medical billing operation. The unit of analysis is ${x.unit}. It does not evaluate clinical care, individual staff merit, legal compliance, contract entitlement, or the correctness of a payer's final decision.`,
 `Methodology: Freeze the population, observation window, source report, filters, cutoff, timezone, duplicate rule, and exclusions before reviewing results. ${x.method} Retain routine cases, exceptions, reopened work, missing evidence, and access failures in the reported denominator.`,
 `Measurement plan: Study ${index+1} reports raw numerators and denominators with every rate. Event time, receipt time, system-entry time, retrieval time, and review time remain separate. Each statement is labeled observed, externally reported, calculated, owner-interpreted, or unknown.`,
 `Reliability check: Give a mixed sample to a second authorized reviewer who cannot see the first classification. Compare cohort membership, source selection, identifiers, dates, calculations, exclusions, and category. Preserve disagreements and document whether resolution required a clarified rule or owner judgment.`,
 `Analysis: Report source-confirmed, conflicting, missing, access-blocked, superseded, interpretation-required, and unresolved results. Keep sequence distinct from cause. A later event can complete a chronology without proving why an earlier event occurred.`,
 `Role boundary: Support staff may retrieve approved evidence, preserve source wording, compare fields, reproduce arithmetic, and prepare a neutral exception. Qualified owners retain coding, coverage, medical-necessity, credentialing, contract, privacy, accounting, submission, refund, write-off, and patient-communication decisions.`,
 `Inference limits: Findings describe only the frozen cohort, systems, definitions, and observation window reported here. They should not be generalized to another payer, team, or period without replication. Association, order, and missing records do not establish causation or responsibility.`,
 `Limitations: ${x.limits} Non-random selection, interface changes, incomplete history, access restrictions, and unresolved records can bias the observed distribution. Unknowns remain visible rather than being removed to improve the result.`,
 `Conclusion: The design can locate an evidence-chain break and frame a bounded question for an authorized owner. It cannot forecast acceptance, payment, appeal success, liability, or clinical correctness.`,
 ...x.sources.map(source=>`Source reviewed September 9, 2026: ${source}`)
]}));
