import type { Metadata } from 'next';
import { notFound, permanentRedirect } from 'next/navigation';
import { Header, Footer, CTA, JsonLd } from '../../components';
import { researchPosts, site } from '../../data';
const researchAliases:Record<string,string>={'research-medical-billing-authorization-unit-variance-2026':'research-medical-billing-sep7-authorization-unit-variance-2026','research-medical-billing-sep1-authorization-unit-variance':'research-medical-billing-sep7-authorization-unit-variance-2026','research-medical-billing-era-import-rejection-recovery-2026':'research-medical-billing-sep7-era-import-rejection-recovery-2026','research-medical-billing-claim-transmission-acknowledgment-gap-2026':'research-medical-billing-sep7-claim-transmission-acknowledgment-gap-2026','research-medical-billing-appeal-receipt-reproducibility-2026':'research-medical-billing-sep7-appeal-receipt-reproducibility-2026'};
const seoTitle=(value:string)=>{const concise=value.replace(/^Medical Billing /i,'');return concise.length<=58?concise:`${concise.slice(0,55).replace(/\s+\S*$/,'')}…`};
const seoDescription=(value:string)=>value.length<=155?value:`${value.slice(0,152).replace(/\s+\S*$/,'')}…`;
const readerDate = new Intl.DateTimeFormat('en-US',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'});
const formatReaderDate=(value:string)=>readerDate.format(new Date(`${value}T00:00:00Z`));
export function generateStaticParams(){return researchPosts.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;if(researchAliases[slug])permanentRedirect(`/research/${researchAliases[slug]}`);const p=researchPosts.find(x=>x.slug===slug);if(!p)return {};const canonical=`https://${String(site.domain).toLowerCase()}/research/${p.slug}`;const hero=p.featuredImage?.replace(/\.webp$/,'.png');return {title:seoTitle(p.title),description:seoDescription(p.excerpt),alternates:{canonical},openGraph:{title:p.title,description:p.excerpt,type:'article',url:canonical,modifiedTime:p.updated,images:hero?[hero]:undefined}}}
export default async function ResearchPost({params}:{params:Promise<{slug:string}>}){const {slug}=await params;if(researchAliases[slug])permanentRedirect(`/research/${researchAliases[slug]}`);const p=researchPosts.find(x=>x.slug===slug);if(!p)notFound();const canonical=`https://${String(site.domain).toLowerCase()}/research/${p.slug}`;const published=p.datePublished||p.published;const hero=p.featuredImage?.replace(/\.webp$/,'.png');return <><Header/><main className="section"><JsonLd data={{'@context':'https://schema.org','@type':'Article',headline:p.title,description:p.excerpt,url:canonical,datePublished:published,dateModified:p.updated||published,image:hero?`https://${String(site.domain).toLowerCase()}${hero}`:undefined,author:{'@type':'Organization',name:site.brand},publisher:{'@type':'Organization',name:site.brand,url:`https://${String(site.domain).toLowerCase()}`}}}/><article className="container guide-article"><p className="eyebrow">Philippines staffing research</p><h1>{p.title}</h1><p className="lead">{p.excerpt}</p>{published&&<p className="article-meta"><time dateTime={published}>Published {formatReaderDate(published)}</time>{p.updated&&p.updated!==published&&<> · <time dateTime={p.updated}>Updated {formatReaderDate(p.updated)}</time></>}</p>}{hero&&<img src={hero} alt={`${p.title} editorial illustration`} width="1536" height="1024" style={{width:'100%',height:'auto',borderRadius:'18px'}}/>}<div className="card">{p.body.map(x=><p key={x}>{x}</p>)}</div>{p.serviceCta&&<aside className="card"><p className="eyebrow">Next step</p><h2>{p.serviceCta.title}</h2><p>{p.serviceCta.body}</p><a href={p.serviceCta.href}>{p.serviceCta.label}</a></aside>}</article><CTA/></main><Footer/></>}
